### ISSUE TITLE
我是不是应该在插件的实际存放位置去解压那个压缩文件

### ISSUE THREAD

**Issue by yunswj** [github0null/eide#1]

**Comment by github0null** [comment]
你好, 是插件自带的解压命令失败了吗？

**Comment by yunswj** [comment]
你看就是这样，还有请教一下使用自动补全的时候&nbsp; &nbsp;单片机对应头文件的存放地址是？



---原始邮件---
发件人: "Null"<notifications@github.com&gt;
发送时间: 2019年10月19日(星期六) 下午4:08
收件人: "github0null/eide"<eide@noreply.github.com&gt;;
抄送: "云深无际"<1827652464@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [github0null/eide] 我是不是应该在插件的实际存放位置去解压那个压缩文件 (#1)



你好, 是插件自带的解压命令失败了吗？

**Comment by github0null** [comment]
头文件存放在插件的安装目录下，为 ./bin/C51 或 ./bin/ARM ，头文件包含是由插件进行管理的；

如果要添加自定义的头文件，你可以在  项目依赖->自定义->default->incList中进行添加

**Comment by yunswj** [comment]
关键还是没有界面显示，在你之前的assign那个版本可以有显示

---原始邮件---
发件人: "Null"<notifications@github.com&gt;
发送时间: 2019年10月19日(星期六) 晚上7:21
收件人: "github0null/eide"<eide@noreply.github.com&gt;;
抄送: "云深无际"<1827652464@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [github0null/eide] 我是不是应该在插件的实际存放位置去解压那个压缩文件 (#1)



头文件存放在插件的安装目录下，为 ./bin/C51 或 ./bin/ARM ，头文件包含是由插件进行管理的；
 
如果要添加自定义的头文件，你可以在  项目依赖-&gt;自定义-&gt;default-&gt;incList中进行添加

**Comment by github0null** [comment]
好的，知道了, 我还在搭建 日志服务器，马上可以开始分析  插件 上传的日志了，谢谢

**Comment by yunswj** [comment]
感谢感谢



---原始邮件---
发件人: "Null"<notifications@github.com&gt;
发送时间: 2019年10月19日(星期六) 晚上7:33
收件人: "github0null/eide"<eide@noreply.github.com&gt;;
抄送: "云深无际"<1827652464@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [github0null/eide] 我是不是应该在插件的实际存放位置去解压那个压缩文件 (#1)



好的，知道了, 我还在搭建 日志服务器，马上可以开始分析  插件 上传的日志了，谢谢
