### ISSUE TITLE
armclang: error:cannot specify -o when generating multiple output files

### ISSUE THREAD

**Issue by WeNeedChinese** [github0null/eide#104]
编译的时候出现
armclang: error:cannot specify -o when generating multiple output files
错误

**Comment by github0null** [comment]
检查你的编译参数里是否有多余的值

**Comment by WeNeedChinese** [comment]
> 检查你的编译参数里是否有多余的值

请问编译参数在哪？有没有相关的资料推荐学习一下？我没有学习过编译原理。

**Comment by github0null** [comment]
![image](https://user-images.githubusercontent.com/43022536/157809125-7239ec2a-92aa-4c16-9a69-935c33c206ed.png)

***

如果编译选项里有不正确的参数的话，可能会导致这种情况

你打开 **构建配置**->**编译器选项** -> **C/C++** 检查一下

**Comment by WeNeedChinese** [comment]
> ![image](https://user-images.githubusercontent.com/43022536/157809125-7239ec2a-92aa-4c16-9a69-935c33c206ed.png)
> 
> 如果编译选项里有不正确的参数的话，可能会导致这种情况
> 
> 你打开 **构建配置**->**编译器选项** -> **C/C++** 检查一下

![image](https://user-images.githubusercontent.com/72389265/157810904-4a8a6756-8843-4a93-b7c6-c6861597dd0b.png)
我检查了我的编译器选项（从keil复制过来的），最后一条命令的确出现-o了，请问这个语句应该怎么修改才能在EIDE上编译？这个语句是什么意思？

**Comment by github0null** [comment]
只留下 `-f` 和 `-w` 开头的参数，其他的全删掉

文档里有描述如何导入项目，https://docs.em-ide.com/#/zh-cn/import_project

Keil 上的勾选框选项，eide 也都有，需要复制的，只有 keil `misc-control` 里的东西

**Comment by WeNeedChinese** [comment]
> 只留下 `-f` 和 `-w` 开头的参数，其他的全删掉
> 
> 文档里有描述如何导入项目，https://docs.em-ide.com/#/zh-cn/import_project
> 
> Keil 上的带有勾选框的选项，eide 也都有，需要复制的只有 keil `misc-control` 里的东西

![image](https://user-images.githubusercontent.com/72389265/157813041-8d5349ad-18bc-4c4d-aaf9-77586c1ae5df.png)
![image](https://user-images.githubusercontent.com/72389265/157813087-b9879bc7-fc21-43e0-b81b-3cfdc7c4bdb4.png)
已经按照教程导入工程和设置相关选项，还是无法在EIDE里面编译，但可以在Keil里面编译。请问keil里面C/C++选项卡下面三行与EIDE下面三行是如何对应的？

**Comment by github0null** [comment]
- 先把这些勾选框，在 eide 的 C/C++ 页面里勾上，没有的先不管

  ![image](https://user-images.githubusercontent.com/43022536/157813826-b1d99288-929d-484b-b75a-8d90cff34ac9.png)

- `Misc-Controls` 里的填到 `编译器附加选项(全局) ` 里

  ![image](https://user-images.githubusercontent.com/43022536/157813783-3aec6d8b-f86c-4faa-a446-88b9c7a541a9.png)

  还剩两个框，因为有时候 C 和 C++ 的一些选项是不兼容的，这时候要分开填在 `C编译器附加选项` 和 `C++编译器附加选项` 里面

**Comment by WeNeedChinese** [comment]
> * 先把这些勾选框，在 eide 的 C/C++ 页面里勾上，没有的先不管
>   ![image](https://user-images.githubusercontent.com/43022536/157813826-b1d99288-929d-484b-b75a-8d90cff34ac9.png)
> * `Misc-Controls` 里的填到 `编译器附加选项(全局) ` 里
>   ![image](https://user-images.githubusercontent.com/43022536/157813783-3aec6d8b-f86c-4faa-a446-88b9c7a541a9.png)
>   还剩两个框，因为有时候 C 和 C++ 的一些选项是不兼容的，这时候要分开填在 `C编译器附加选项` 和 `C++编译器附加选项` 里面（导入的 Keil 项目一般不用管这个）

在按要求重新导入之后出现以下问题：
![image](https://user-images.githubusercontent.com/72389265/157822646-ca8e284b-dc61-42dc-b4d5-1ebba93a3ba5.png)

请问是不是因为没有下载芯片支持包或者我导入芯片支持包的位置不对导致这个宏定义没有开启，出现编译错误。

**Comment by github0null** [comment]
检查一下 `宏定义` 是否导入过来了，没有的话，手动加上，你之前发的参数中是有 `ARMCM4` 宏的

![image](https://user-images.githubusercontent.com/43022536/157823703-0573eaad-ebfc-45e6-89b6-b6e657f56319.png)

**Comment by WeNeedChinese** [comment]
> 检查一下 `宏定义` 是否导入过来了，没有的话，手动加上，你之前发的参数中是有 `ARMCM4` 宏的
> 
> ![image](https://user-images.githubusercontent.com/43022536/157823703-0573eaad-ebfc-45e6-89b6-b6e657f56319.png)

调试了一个下午之后终于编译成功了，总结以下就是项目属性文件要加上芯片型号，并且把没有成功导入的文件导入到原来的位置，构建器选项也要一一对应，感谢大佬的耐心指导！
