### ISSUE TITLE
串口工具接收中文内容乱码

### ISSUE THREAD

**Issue by Antecer** [github0null/eide#105]
![image](https://user-images.githubusercontent.com/8684916/158605902-26348ec2-ed29-4070-baf3-7ef76d9099bf.png)
如图，有什么解决办法吗？

**Comment by github0null** [comment]
把源文件的改成 GBK 格式的，vscode 状态栏右下角显示是 UTF-8 的

**Comment by Antecer** [comment]
确实解决了问题，如果能让串口工具自动适配源文件编码就好了，或者允许用户设置数据编码。
