### ISSUE TITLE
MDK ThreadX项目编译失败

### ISSUE THREAD

**Issue by CaiHua1995** [github0null/eide#106]
STM32 CubeMX 生成的普通项目然后自己移植了threadx，在mdk上可以编译通过，在vscode编译提示threadx内部的汇编文件编译错误，在构建器里面将汇编器类型改为asm-clang后threadx内部汇编文件可以编译通过，但是STM32启动文件又编译失败。
![编译失败1](https://user-images.githubusercontent.com/31735488/159106119-bd8a38f1-1a70-47cc-b379-970783976364.png)
![修改汇编编译器](https://user-images.githubusercontent.com/31735488/159106123-c18872c6-f215-4b67-ae27-5e5009fcc335.png)
![编译失败2](https://user-images.githubusercontent.com/31735488/159106127-d0dd9f3a-1220-4998-96c3-0c4bdac66aa3.png)

**Comment by CaiHua1995** [comment]
链接：https://pan.baidu.com/s/1-jRpD67GRT8jsrfI21FdYQ 
提取码：vctc
这个是整个项目文件我把它放在了百度云盘

**Comment by github0null** [comment]
这个插件是不能为单个源文件设置用什么编译器的，只能全局设置；threadx 汇编是 gcc 的，你的 cubemx startupxx.s 用的 armcc 汇编，

**Comment by CaiHua1995** [comment]
好吧！threadx 汇编是armcc v6 但是cubemx startupxx.s 好像还是老版本的！在MDK里面设置成 v6编译器编译是没问题的

**Comment by github0null** [comment]
你可以把先把 `startup_stm32f407xx.s` 用 armcc5 编译成 `.o`，添加到项目里，然后直接用 armcc6 编就行了

![image](https://user-images.githubusercontent.com/43022536/159197245-872f242a-f207-4282-985d-552d29f51a04.png)

**Comment by CaiHua1995** [comment]
好的！谢谢

**Comment by TP-Thread** [comment]
可以在EIDE里添加arm-clang(arm syntax)吗？
![image](https://github.com/github0null/eide/assets/122875991/3b4a0a21-5e32-46c8-99d1-1e834dcdc22e)

**Comment by jmdweem** [comment]
> 可以在EIDE里添加arm-clang(arm syntax)吗？ ![image](https://github.com/github0null/eide/assets/122875991/3b4a0a21-5e32-46c8-99d1-1e834dcdc22e)

同样希望加入Arm Syntax的选项
