### ISSUE TITLE
能支持makefile项目的导入或者在项目中加入嵌入makefile的选项

### ISSUE THREAD

**Issue by gitQqqHs** [github0null/eide#111]
最近做键盘固件，qmk固件使用了chibios，但是我要自己适配chibios的底层驱动。
尽管官方有自己的studio，但是太重了，对调试器的支持也有问题。当然，我的MCU也很冷门
eide的项目做的很不错，上手即用，但是对于有很多rules.mk文件的项目来说，要全部转换过来，工作量太大了
在eide项目配置文件中加入对makefile的调用，看来是个不错的选择。
既不用大量修改文件，也能适配大量使用makefile配置的项目。
我觉得还是可行的。

**Comment by github0null** [comment]
eide插件实现了两个功能：
 - 构建系统：提供一种能够描述项目的文件，然后根据这个文件能够编译项目
 - IDE支持：能够整理出项目的编译过程信息，提供给C/C++插件，用来给项目提供智能感知，补全，跳转功能

而 makefile 本身就与这个插件有冲突：
- makefile 已经是一种**构建系统**了
- vscode 上有 `Makefile tools` 插件，能够为 Makefile 项目提供智能感知，补全，跳转等功能，因此 **IDE 支持** 也已经满足了

***

因此如果是 makefile 工程，可以直接使用 `Makefile tools` 插件，也能达到一样的效果，没必要用 eide 插件，这个插件只是提供了一种不同的选择
