### ISSUE TITLE
Gets a Trojan Horse Warning from Antivirus

### ISSUE THREAD

**Issue by vishnumaiea** [github0null/eide#114]
Installed this extension and suddenly I got a threat warning from Avast. It complains that **memap.exe** is infected by some malware.

![image](https://user-images.githubusercontent.com/10383395/164215686-2d52b047-85ea-4359-bf97-7a49e046a130.png)

**Comment by github0null** [comment]
@vishnumaiea 

`memap.exe` is build by PyInstaller.  This may be a false positive. 

https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg

This program used to parse *.map files. like this:

![image](https://user-images.githubusercontent.com/43022536/164216975-da93b415-61ad-4f55-bef8-5d774423289f.png)

**Comment by vishnumaiea** [comment]
I have reported a false positive.
