### ISSUE TITLE
编译找不到头文件

### ISSUE THREAD

**Issue by yaoshila** [github0null/eide#12]
keil中可以编译，导入keil工程后在自定义依赖中也看到了所需依赖，但是编译不通过，找不到头文件。。。
 > Compile: stm32f10x_it.c...
"c:\Users\Wu_Wi\Desktop\233\Target 1\.\src\User\stm32f10x_it.c", line 25: Error:  #5: cannot open source input file "stm32f10x_it.h": No such file or directory
  #include "stm32f10x_it.h"
                            ^
c:\Users\Wu_Wi\Desktop\233\Target 1\.\src\User\stm32f10x_it.c: 0 warnings, 1 error

**Comment by github0null** [comment]
可以在自定义依赖中添加头文件的路径，再编译， 头文件这种问题一般都很好解决的，没找到添加一下就可以了，在下个版本会解决这个问题的
