### ISSUE TITLE
可否支持eclipse工程导入

### ISSUE THREAD

**Issue by zerosensei** [github0null/eide#121]

**Comment by github0null** [comment]
`eclipse` 我就没用明白过，它工作方式太混乱了，目前是做不了支持的

不过插件提供了扩展的导入功能，如果你很熟悉 eclipse 的工程，可以自己按照接口写好 js 脚本去导入源文件树结构

https://docs.em-ide.com/#/zh-cn/project_manager?id=%e4%bb%8e%e5%85%b6%e4%bb%96-ide-%e9%a1%b9%e7%9b%ae%e5%af%bc%e5%85%a5%e6%ba%90%e6%96%87%e4%bb%b6%e8%b5%84%e6%ba%90
