### ISSUE TITLE
尝试运行插件源码时遇到插件激活失败问题

### ISSUE THREAD

**Issue by Darkycl** [github0null/eide#122]
Activating extension 'cl.eide' failed: Cannot find module 'e:\Embedded\EIDE\eide\dist\extension.js'
Require stack:
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js.

项目路径下没有dist文件夹

**Comment by github0null** [comment]
你不用 webpack 编译怎么调试呢，参考 vscode 插件开发指南

对于本项目，打开 `ctrl+shift+b` 打开 task 列表，选择：npm webpack 即可：

![image](https://user-images.githubusercontent.com/43022536/167402936-5cb9f819-3233-40d1-8218-9e03f01072ca.png)
