### ISSUE TITLE
遇到中文字符会报错

### ISSUE THREAD

**Issue by wpmyj** [github0null/eide#13]
const USER_GENERAL_CONFIG_T sUserConfigDefaultT = 
{
	{ 0 },									// 虚拟ID
	"自定义字符段(16个汉字或32个字符)",		// 自定义字符段
	
	60,										// 数据采集周期
	0,										// 预留
	
	100000,									// 粉尘仪 K 值
};
Error:  #144: a value of type "char [46]" cannot be used to initialize an ent

**Comment by github0null** [comment]
你这是语法问题，跟插件无关，插件使用的是 Keil 的编译器

**Comment by wpmyj** [comment]
这个不是语法问题，我在MDK Keil下编译是正常的，EIDE下我把它改成英文字符串就没有问了

**Comment by github0null** [comment]
可能是没有加上一些编译配置，会改进的
