### ISSUE TITLE
有计划支持 rt-thread 吗？

### ISSUE THREAD

**Issue by maikebing** [github0null/eide#136]
1. 比如 rt-thread 的一些命令行， 或者是 他生成的 KEIL  文件的实时同步等。  
2. 打开 STM32CubeMX 文件的快捷方式， 打开后运行rt-thread 的处理脚本等。 

之所以提这个建议， 是我觉得rt-thread 的项目没法跟 keil   感觉不怎么灵活。

**Comment by github0null** [comment]
rt-thread 使用 scons 作为构建系统，和这个是不能兼容的

用 rt-thread 也根本不需要这个插件，scons 会生成 `compile_commands.json`，将这个文件直接加到 `c/c++` 配置中就可以浏览代码，使用跳转，补全功能了

***

这个插件的目标是为了给 `不使用 makefile, scons, cmake ...` 等构建系统的用户提供一个选择，在 vscode 上提供项目的管理和编译功能

**Comment by github0null** [comment]
- 对于 rt-thread 这种有包管理，软件生态的，还是用官方的开发工具比较合适

- 对于 rt-thread nano 这种只带裸系统的，eide 插件本来就提供了项目模板的

**Comment by maikebing** [comment]
感谢。
