### ISSUE TITLE
【建议】在添加外设组件时，增加一步检查 .eide\deps 是否在srcDirs中

### ISSUE THREAD

**Issue by laognf95** [github0null/eide#137]
在尝试忽略库文件的时候。。 直接忽略掉deps，再重新clone回来

打开工作区的时候，ide会从srcDirs自动删除掉不存在的.eide\deps

这个文件夹是在创建工程的时候自动加入srcDirs的，并且可能是因为在二级目录？并不会在重新创建的时候自动增加回去

导致编译的时候找不到组件

**Comment by github0null** [comment]
这个地方后面会优化一下的，后面我在添加组件前自动检查一下就行了

***

之前是会在打开项目前强制添加 .eide/deps 目录到项目的，只是后面不再这样做了，因为有些人不用这个功能，强制性添加的东西不太合适

https://github.com/github0null/eide/commit/75d27718376e7200afc699d40aca124e59b06ef0?diff=unified#diff-629cdf62f710c3be368f4eaa7d0307de0f6e4b15949283463874b0fdbd1542b0L886

![image](https://user-images.githubusercontent.com/43022536/173016978-05132226-dc8a-4231-87e3-f3fce91c23d8.png)
