### ISSUE TITLE
macOS ?

### ISSUE THREAD

**Issue by Code-alluring** [github0null/eide#138]
macOS ?

**Comment by github0null** [comment]
https://discuss.em-ide.com/d/253-mac

macOS 后续有时间再支持，目前我还没有接触过 macOS

**Comment by Code-alluring** [comment]
可以运行一个 macOS 的虚拟机

**Comment by Code-alluring** [comment]
> https://discuss.em-ide.com/d/253-mac
> 
> macOS 后续有时间再支持，目前我还没有接触过 macOS
可以运行一个 macOS 的虚拟机
