### ISSUE TITLE
如何配置程序存储器的代码偏移？

### ISSUE THREAD

**Issue by Antecer** [github0null/eide#143]
如图，这是Keil的配置选项：
![image](https://user-images.githubusercontent.com/8684916/179394879-6ef779cd-ad72-4670-ae7c-4352e2e211af.png)

需求是将编译后的程序代码放入指定的ROM地址段。

**Comment by github0null** [comment]
这个些选项，Keil 会生成 链接参数，将右图中的 `CODE(...) ...` 这些参数复制到 eide 的 构建配置 -> Linker 配置页面 -> `Other Linker Options` 中就行了

![image](https://user-images.githubusercontent.com/43022536/179395547-3b546289-04f2-4e21-8ca3-470a3a30312a.png)

**Comment by Antecer** [comment]
![image](https://user-images.githubusercontent.com/8684916/179396577-f73501b4-2f10-4ed5-ac92-a698092f2ecf.png)
![image](https://user-images.githubusercontent.com/8684916/179396590-56fada8f-7705-4975-9634-be1c71028a7e.png)
链接器参数拷贝过来，编译出错。

**Comment by github0null** [comment]
去掉 逗号 ',' 再试

**Comment by Antecer** [comment]
![image](https://user-images.githubusercontent.com/8684916/179397277-44e43028-8773-4d27-bdfe-02053117577c.png)
还是不行

**Comment by github0null** [comment]
刚看了一下，Keil 做了预处理的，你要先输出 `.lnp` 参数文件，然后再看

勾上 `output BAT` 之后，点编译，会生成 `.lnp` 文件到工程目录下

![image](https://user-images.githubusercontent.com/43022536/179397473-131ee49f-259f-4bf8-b068-7d6d167bc021.png)

**Comment by Antecer** [comment]
成功了，用 CLASSES() 把参数都包括起来就正确了。
