### ISSUE TITLE
feature request about importing keil project

### ISSUE THREAD

**Issue by TheSnowfield** [github0null/eide#152]
I found EIDE always ignores the `Misc controls` option of the arm compiler and linker while importing the keil project.
![5@2XMOWSU5OD)QL(9@XV92X](https://user-images.githubusercontent.com/17957399/184519074-bc0acc35-bf10-4a7b-a268-0992d1d71357.png)
![`~IPK0WXWMU3JPY5U84S~P0](https://user-images.githubusercontent.com/17957399/184519081-f7dcf5bd-16b3-402c-9dc7-aabdaa1fcac4.png)

they can cause fatal compiling or linking errors in some cases. 
now I can add them to eide builder options manually but I have cost the whole night tracking the issue.

I tried to fork and create a PR, but I cannot deal with the code. I guess the Keil XML parser seems cannot pass the extra arguments to the build options, they're the two independent parts beyond my scope of work.

so the feature request comes. :3

**Comment by github0null** [comment]
这个文档里本来就有说明：
https://docs.em-ide.com/#/zh-cn/import_project

**Comment by TheSnowfield** [comment]
> 这个文档里本来就有说明： https://docs.em-ide.com/#/zh-cn/import_project

doc確實沒什麽問題, 但是導入工程的時候這些字段完全是可以被解析的,
並且這些選項在 build option 中也可以被手動設置, 導入的時候故意丟掉這些字段, 個人感覺有一點不符合邏輯。
倘若只是因爲架構問題暫時不好去實現它, 那好像也沒什麽別的辦法了。
