### ISSUE TITLE
更新过后，无法link lib文件

### ISSUE THREAD

**Issue by ckforce** [github0null/eide#153]
--cpu SC000 --library_type=microlib --scatter "./APP.sct" --entry=Reset --strict --summary_stderr --info summarysizes --map --xref --callgraph --symbols --info sizes --info totals --info unused --info veneers --list .\build\app.map
![image](https://user-images.githubusercontent.com/22431888/184786227-baa8ec94-5e94-4c53-b3d4-5a8cee15468e.png)

配置了库路径，但是link命令行里面并没有出现

**Comment by github0null** [comment]
- 添加 lib: https://em-ide.com/zh-cn/docs/modules/project_resource/#%E6%B7%BB%E5%8A%A0%E6%BA%90%E6%96%87%E4%BB%B6

- 链接库目录含义: https://em-ide.com/zh-cn/docs/modules/project_attr#%E5%BA%93%E7%9B%AE%E5%BD%95

**Comment by ckforce** [comment]
之前版本可以把整个目录添加进去就可以，现在需要改成添加文件，然后单独lib文件就可以了。感谢
