### ISSUE TITLE
在WSL2中获得的代理地址是Windows的

### ISSUE THREAD

**Issue by stars-under** [github0null/eide#154]
如图,使用VSCode的WSL插件连接到ubuntu后,插件找到的代理地址是windows主机的
![image](https://user-images.githubusercontent.com/53163647/185287504-8abfcfcf-8d31-4750-867a-0814d33a8d5a.png)

**Comment by stars-under** [comment]
![image](https://user-images.githubusercontent.com/53163647/185288193-fc027fd3-ce5b-43d6-be99-50e587a3666a.png)
这是ubuntuhan环境配置的代理地址

**Comment by stars-under** [comment]
目前暂时的解决办法是使用端口映射工具把ubuntu的代理端口映射到Windows上

**Comment by github0null** [comment]
你应该去调整 VSCode 代理配置，因为插件运行在 VSCode 的 Node 环境中

你的 log 上显示的也是 `vscode-server` 里抛出的错误

**Comment by stars-under** [comment]
调整该选项后,问题解决了
![image](https://user-images.githubusercontent.com/53163647/185296854-25aad0d4-de56-44d8-8864-014e2bfac893.png)
