### ISSUE TITLE
[question] 多目标编译如何把${ConfigName}加到目标文件名上

### ISSUE THREAD

**Issue by ckforce** [github0null/eide#159]
rt

**Comment by github0null** [comment]
在构建配置中增加一个 `post-build` task，复制文件并重命名

**Comment by ckforce** [comment]
其他没有办法嘛😂




| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月29日 16:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [github0null/eide] [question] 多目标编译如何把${ConfigName}加到目标文件名上 (Issue #159) |

在构建配置中增加一个 post-build task，复制文件并重命名

**Comment by github0null** [comment]
不知道你要干什么，提问也不按模板

但这就是最好的办法，`post-build` 就是用来给用户去处理编译生成的产物的

加时间戳，计算 crc，生成特定格式文件，这些操作都可以用这个完成

**Comment by ckforce** [comment]
post-build实现没问题，只是希望能更加简洁一点
