### ISSUE TITLE
有没有支持Cmake 工程的计划？

### ISSUE THREAD

**Issue by hongshui3000** [github0null/eide#160]
有没有支持Cmake 工程的计划？配合微软的vscode-cmake-tools扩展

**Comment by github0null** [comment]
要用 CMake 了为什么还需要 IDE，放在一起打架吗？

**Comment by hongshui3000** [comment]
CLion 就是很好的例子

**Comment by github0null** [comment]
Visual Studio, CLion 这种增加的 CMake 功能，主要是增加一些 cmake 补全，提示，以树的形式展示项目结构，提供一些快捷键来执行 cmake 命令

在 VSCode 上，`vscode-cmake-tools` 插件已经实现这些功能

eide 这个插件有自己的生成器和构建流程，比较适合像 iar, mdk 那样建项目

如果你要用 cmake，`vscode-cmake-tools` 就足够了

**Comment by hongshui3000** [comment]
vscode-cmake-tools 工程管理能力有点弱，我才想着有个cmake的ide有多好
