### ISSUE TITLE
Unable to build the example with STM8S103 and SDCC for debug

### ISSUE THREAD

**Issue by mkSaBtsy** [github0null/eide#161]
After discovering EIDE in Visual Studio Code I want to debug STM8 microcontroller with ST-LINK. I'm using SDCC and I have already successfully built hex-files and flashed it to the uC. But I need to debug them as well.

Unfortunately I'm not even able to build the example for the STM8S103 CPU in debug configuration. I instantly get the error **"Invalid '$use' option!,please check compile option 'linker.$use'"**

I found the option "$use" in linker parameters in the file builder.params. So I triedt to delete the '$use' option because it is not recognized by SDCC. Alas, this file seems to be auto generated. After I attemp to build the configuration the '$use' parameter is added agin to the linker parameters.

Does anyone have a suggestion for me?

**Comment by github0null** [comment]
I have fixed it.

Restart VSCode, eide will fetch update for `eide-binaries` and update to `8.3.4`

**Comment by mkSaBtsy** [comment]
Dear github0null,

Great thanks for the quick fix. 
Now I can at least build the debug configuration. However, the executing path for the "sdcc fix elf" task seems to be wrong in the template. It only work if I manually correct the path to the "stm8-objcopy.exe" that I searched in the .eide folder. Maybe the template has to be adapted.

Not working preset in the template:
![grafik](https://user-images.githubusercontent.com/38809530/188308152-66bb85a3-e90b-43be-b6ed-40c922bf565d.png)
Output in terminal:
![grafik](https://user-images.githubusercontent.com/38809530/188308084-5e925cca-f1c2-4173-b27c-ee621072c993.png)

Workaround that worked for me:
![grafik](https://user-images.githubusercontent.com/38809530/188308127-19d84949-6b3b-4c4c-8d26-12251cc950af.png)
Output:
![grafik](https://user-images.githubusercontent.com/38809530/188308214-eee8db09-c07a-4eae-9d00-93bc8fe6c2a4.png)

Unfortunateli I'm still unable to actually debug my chip. Although I put the openocd - .cfg- files for my chip in every folder mentioned there: 
https://em-ide.com/docs/modules/flasher#specific-configurations 
I don't get openocd to choose as "flasher-configuration". See here:
![grafik](https://user-images.githubusercontent.com/38809530/188308455-b70fb3d5-a3d9-4032-8ee6-6f5577f9a27a.png)
I even tried to put separately downloaded binaries for openocd into the folder configured in the eide plugin settings.
Can you give me a hint please?

**Comment by github0null** [comment]
This template is maybe too old, some env variables are deprecated

You need remove `${ExeDir}` env, only use `stm8-objcopy.exe`, because this exe is already in system path.

![image](https://user-images.githubusercontent.com/43022536/188311066-6af8e5f1-707e-410a-a2a0-94bee8cf3825.png)

**Comment by github0null** [comment]
There are all available env variables:

https://em-ide.com/docs/modules/builder#user-task-variables

**Comment by github0null** [comment]
>Unfortunateli I'm still unable to actually debug my chip. 

This plug-in can't debug your chip, it's only can `build`, `program flash`

You need other debugger plug-ins

**Comment by github0null** [comment]
> I don't get openocd to choose as "flasher-configuration". See here:

Now we not support openocd for `8BIT Project` !
![image](https://user-images.githubusercontent.com/43022536/188321592-212bb8bd-f85c-4573-81c5-2d6b76601c1d.png)


You can use any shell command to flash your board by `Shell Flasher` !
![image](https://user-images.githubusercontent.com/43022536/188321526-429ed7c9-55ae-495d-bc64-5ca221ecbd1d.png)

**Comment by mkSaBtsy** [comment]
> Now we not support openocd for 8BIT Project !

Ah, I see. Indeed, thanks to your plugin I'm able to flash STM8-chips in a comfortable way.

> This plug-in can't debug your chip, it's only can build, program flash

Since your answer I'm trying to get the STM8-debug plugin to work. 

Thanks a lot for your explanations.
