### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bjwanghao** [github0null/eide#170]
- Issue Type: `Performance`
- Extension Name: `eide`
- Extension Version: `3.9.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.71.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///d%3A/toolchain/VSCode-win32-x64/data/tmp/cl.eide-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by github0null** [comment]
请提交你的 `.cpuprofile.txt` 文件

**Comment by github0null** [comment]
未回复，已关闭
