### ISSUE TITLE
希望可以增加对C251的支持

### ISSUE THREAD

**Issue by Six-6Chen** [github0null/eide#173]
![1](https://user-images.githubusercontent.com/78344034/193447581-f7dbc284-506e-43fc-a9e2-3cd98da951e7.png)
通常我会安装多个编译工具链我的STC32G64K128 是C251 希望可以支持

**Comment by github0null** [comment]
已经回答过了：https://github.com/github0null/eide/issues/171#issuecomment-1257124567
