### ISSUE TITLE
keil新建文件夹或者文件新增或删除后，EIDE项目资源目录刷新问题

### ISSUE THREAD

**Issue by diqiu114** [github0null/eide#176]
# 我将工程导入至EIDE中后，项目资源一栏的文件夹是这样的：
![image](https://user-images.githubusercontent.com/64526164/197145960-c791a9e8-96fb-4e5c-919a-016af730ef24.png)
# 与keil中项目文件匹配：
![image](https://user-images.githubusercontent.com/64526164/197146100-825351c6-aedc-4ee7-affd-9acf0cffc48e.png)
# 当我变更keil中的文件目录结构时：
![image](https://user-images.githubusercontent.com/64526164/197146291-b178cb42-2011-4101-8ec1-9493259305d9.png)
# 然后在EIDE中进行刷新后
![image](https://user-images.githubusercontent.com/64526164/197146384-eaf97110-3497-4bbe-9013-954215b8e979.png)
# 项目资源的文件目录没有变化
![image](https://user-images.githubusercontent.com/64526164/197147339-b1d50cd8-14f9-4282-8657-a4216728addc.png)
# 后记：如果有这个功能，希望哪位大佬踢我一脚，告诉我一声，如果没有，渴望能够添加这个实时刷新的功能

**Comment by github0null** [comment]
没有这样的功能，也不应该有这样的功能

这个插件不是 keil 的 vscode 版本，这是一款独立的插件，有自己的项目文件，构建、烧录流程；如果使用 gcc 编译器，则不会依赖任何跟 keil 有关的东西

你应该读一下文档
