### ISSUE TITLE
建议增加macos的支持

### ISSUE THREAD

**Issue by cytown** [github0null/eide#18]
可以调用sdcc等工具

**Comment by github0null** [comment]
作者还没用过 mac book, 不了解 mac os 的相关特性 , 因此暂时还支持不了 mac os

**Comment by cytown** [comment]
这，有点out了。不过用linux也一样的，没太大区别。不要告诉我没法装linux吧。。。

**Comment by cytown** [comment]
对了，有个C51的项目，你可以参考下，是支持多环境的，用的sdcc

**Comment by github0null** [comment]
好的，其实一开始我打算使用gcc的工具链的，这样就可以支持更多平台，但是发现想要自动生成链接脚本不太容易，于是使用的 keil 的 ARMCC, 它的链接脚本比较容易自动生成

**Comment by cytown** [comment]
gcc配置太麻烦了，还是sdcc省事太多了。其它平台有platformio这样的强大ide搞定了，缺的就是51系列的ide。
