### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MoKolberg** [github0null/eide#180]
- Issue Type: `Performance`
- Extension Name: `eide`
- Extension Version: `3.10.0`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.72.2`

[cl.eide-unresponsive.cpuprofile.txt](https://github.com/github0null/eide/files/9873289/cl.eide-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by github0null** [comment]
Thanks for your clues.

I checked this profile, i found that you are executing `Configure Toolchain` function

![image](https://user-images.githubusercontent.com/43022536/198170869-083fa75c-9d1d-465d-952a-a45999bef292.png)

This function will use `platform.find()` to find executable file path in `System Path`

The `find()` function use system command `where`(win32) or `which`(linux) to search.

https://github.com/github0null/eide/blob/6839e0727a67d07881debbd6230134cdf1c1d8f6/src/Platform.ts#L232-L251

When you execute `Configure Toolchain` function one time, we will call `find()` (8 times) to search all the toolchains.

If you use this function frequently, it maybe causes high cpu usage.

![image](https://user-images.githubusercontent.com/43022536/198170437-d11f787b-4822-4126-b3cc-fe346a7bc125.png)
