### ISSUE TITLE
RISCV will not use my compiler, always uses oldname

### ISSUE THREAD

**Issue by duaneellissd** [github0null/eide#183]
**What are you doing?**
When specifying the compiler location (directory)
the user needs to be able to also specify the Compiler prefix

**Describe the bug**
I specified the location of the RISCV compiler I need to use.
In my case it is: C:\Microchip\SoftConsole-v2021.1\riscv-unknown-elf-gcc\bin
The prefix, and thus, GCC is:
C:\Microchip\SoftConsole-v2021.1\riscv-unknown-elf-gcc\bin\riscv64-unknown-elf-gcc.exe

However, the tool(IDE) wants: this
"C:\Microchip\SoftConsole-v2021.1\riscv-unknown-elf-gcc\bin\riscv-none-embed-gcc.exe"

Where in the IDE do I set the correct prefix?

**To Reproduce**
CLEAN, then BUILD - the contents of 'build/debug/build.params' is replaced/re-wrote

Evidently, I am updating the *wrong* location for the compiler prefix.
But - I cannot find this in any of the "json" files in the project directory.
It always reverts back to:   "toolPrefix": "riscv-none-embed-"
which is not the compiler that I need to use.
**Expected behavior**
The ability to specify my GCC compiler prefix.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10]
 - EIDE ?? Just installed it 10/26/2022
 - VSCode Version [e.g. v1.72.1]

**Additional context**
some logs, like: `<user_home>/.eide/cl.eide.log`

IT SEEMS - that (A) the details about the compiler comes from the IDE install directory.
I need to have the PROJECT specify 100% of the tools in the project.
For example, I have 4 different RISCV tools installed, and each project uses a different set of tools - I have no choice in this matter, the tool chain for the project must be frozen and not change. This does not seem possible with this IDE ... the reasons I need to do this, is there are many qualifications the software must go through after we build it and these qualifications are very costly.  A maintenance update (ie: bug fix) cannot change the compiler without a full on total system level regression and re-validation (which for us is a months long very expensive process). But it sure seems that the IDE tool wants to install a non-approved tool chain which is problematic for me!

**Comment by github0null** [comment]
docs: https://em-ide.com/docs/advance/plug-in_settings/#setup-gcc-compiler-prefix
