### ISSUE TITLE
打开工程目录的时候会导致其他插件加载很慢或者根据就加载不了，要点一下EIDE刷新按钮才能

### ISSUE THREAD

**Issue by guangjieMVP** [github0null/eide#184]
打开工程目录的时候会导致其他插件加载很慢或者根据就加载不了，要点一下EIDE刷新按钮才能很快地加载其他插件

**Comment by github0null** [comment]
已经有人提过类似的问题了，请按照链接中的格式附上 cpuprofile 文件帮助我检查扩展的性能问题

https://github.com/github0null/eide/issues/180

对于性能较弱的电脑，可能出现上述链接中的问题，下个版本中将对该问题进行优化

**Comment by github0null** [comment]
还有你可以试一下预览版：`3.10.2` 看看有没有这样的问题
