### ISSUE TITLE
建议自带一个python虚拟环境

### ISSUE THREAD

**Issue by yunline** [github0null/eide#185]
把pyocd与其一大堆依赖库装在全局环境里是很糟糕的做法。建议自带一个虚拟环境，把pyocd等库安装在其中，方便管理。
而且就目前来看，pyocd必须手动输入pip install来安装，能否像openocd一样实现一键安装呢？

**Comment by github0null** [comment]
pyocd 本来就是要安装到全局的，挺方便的呀，python 都是这样

而且插件自带的环境的话，包太大了，影响安装速度，服务器的带宽不够

**Comment by yunline** [comment]
> 
> pyocd 本来就是要安装到全局的，挺方便的呀，python 都是这样
> 
> 而且插件自带的环境的话，包太大了，影响安装速度，服务器的带宽不够
> 
> 
>   

“插件自带虚拟环境”不是指插件自己带一个python解释器，而是使用`python -m venv`指令，生成一个虚拟环境，不会造成服务器的下载负担。  

全局环境不宜安装太多库（想象这样的场景：pip list出来，一整页的库，其中日常用到的就几个，剩下全是没见过的莫名其妙的依赖库）。如果全局环境中有任何库出现报错需要重装，就需手动翻pip list，找到依赖，手动pip uninstall，极其麻烦。而如果安装在虚拟环境里，与全局环境隔离开，就能保证全局环境足够干净。  

故建议把**大多数项目都可能用到的库**安装在全局环境，把**只有少数项目会用的的库**放在独立的虚拟环境里。  

pyocd在大多数情况下属于后者，安装在全局环境中会导致全局环境变得臃肿，不方便库管理。  

关于python虚拟环境，可以参考[这篇文章](https://zhuanlan.zhihu.com/p/56893672?utm_id=0)以及[官方文档](https://docs.python.org/zh-cn/3/tutorial/venv.html)。

**Comment by github0null** [comment]
但是 pyocd 和 python 环境原本就是要用户自己搞定的啊，

插件只是负责发送 shell 命令到 vscode 终端（如果需要自己定制命令，使用 shell 烧录器就行了），而且插件本身不需要 python 环境，只是 pyocd 这个外部的工具需要

或者你可以用 pyinstaller 将 pyocd 打包成单文件程序，这样就不会打乱你的环境
