### ISSUE TITLE
编译失败，找不到.A51文件

### ISSUE THREAD

**Issue by wherewhere** [github0null/eide#19]
小白一个，不知道发生了什么，别人用的都很正常，一脸懵逼。。。
```
[ INFO ] Source file list:
 WARNING  Not found C51 Startup File! File must be named like this: xxx.A51
 ERROR  生成失败(build Failed) : Not found source file
```
![屏幕截图_612_.png](https://i.loli.net/2020/01/10/SAOhidBe7s34Qpa.png)

**Comment by github0null** [comment]
> 看提示是没有找到源文件，可能是路径的权限问题，暂时不清楚
> 中文和带空格的路径是支持的，我的就没问题

![t](https://user-images.githubusercontent.com/43022536/72135870-6c305400-33c2-11ea-8478-247588c61b39.png)

**Comment by wherewhere** [comment]
> > 看提示是没有找到源文件，可能是路径的权限问题，暂时不清楚
> > 中文和带空格的路径是支持的，我的就没问题
> 
> ![t](https://user-images.githubusercontent.com/43022536/72135870-6c305400-33c2-11ea-8478-247588c61b39.png)

是不是keil在C盘的原因呢？

**Comment by github0null** [comment]
有可能是的，c 盘是系统目录，在访问其他目录时有时候没有权限访问，就会导致未知的问题
建议把 工程，Keil 安装在 其他盘

**Comment by github0null** [comment]
工程直接移动一下文件夹就行

**Comment by wherewhere** [comment]
> 有可能是的，c 盘是系统目录，在访问其他目录时有时候没有权限访问，就会导致未知的问题
> 建议把 工程，Keil 安装在 其他盘

表示我就一个盘😂😂😂

**Comment by github0null** [comment]
在C盘根目录自己新建文件夹也是可以的，自己新建的默认没有权限要求

**Comment by wherewhere** [comment]
> 在C盘根目录自己新建文件夹也是可以的，自己新建的默认没有权限要求

好的，我试试。。。

**Comment by wherewhere** [comment]
放在SD卡里也不行。。。。
![屏幕截图_614_.png](https://i.loli.net/2020/01/10/xgTjkML3D7dI5nN.png)

**Comment by github0null** [comment]
这就很奇怪了，还没遇到过这样的问题。。。

**Comment by wherewhere** [comment]
> 这就很奇怪了，还没遇到过这样的问题。。。

很奇怪，第一次编译可以成功，第二次开始就找不到文件了。。。
![屏幕截图_617_.png](https://i.loli.net/2020/01/12/n3Bxg1Df6KHbVeq.png)

**Comment by github0null** [comment]
这个问题暂时不清楚
> 因为这个问题没法在我的电脑上重现，没法知道问题在哪

**Comment by github0null** [comment]
建议换台电脑试试
