### ISSUE TITLE
谢谢大神的努力，就是有个小问题

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [github0null/eide#190]
可不可以加入一个使用原生SDCC风格的8051.h和8052.h的项目模板啊
刚刚习惯了SDCC又要改过去
还有个问题就是第三方头文件要放到哪里？
还有就是设置编译器的时候最好加个提示“定位到根目录而不是bin”

**Comment by github0null** [comment]
- 你直接 删掉自带的 reg52.h，使用 `#include "8051.h"` 就行了
- 怎样添加源文件，包含路径，请看一下文档，keil 上怎么操作，这个就是怎么操作的
- 本来有提示（文档里也专门做了说明），要求设置安装目录路径，就是你安装 SDCC 软件时选的路径，也就是软件的根目录

文档：https://em-ide.com/zh-cn/docs

**Comment by Dawn-Xu-helloworld** [comment]
谢谢大神指点，已经去看文档啦，issue就关了吧
