### ISSUE TITLE
Support for other compilers

### ISSUE THREAD

**Issue by elabdess** [github0null/eide#195]
Is it possible to use eide with other eclipse-based projects like Renesas CCRX/GCC RX projects, (e2studio)?

or how to add support for another toolchain and parse this type of .cproject file.

I can provide any information and project example.

[test_project.zip](https://github.com/github0null/eide/files/10217516/test_project.zip)

**Comment by github0null** [comment]
1. You need to use `import project` function, and select `Eclipse`, then import .cproject file
  docs: https://em-ide.com/docs/getting-started/import_prj#eclipse-project

2. Open vscode workspace file: `xxx.code-workspace` file, 
  add `EIDE.Toolchain.AnyGcc.InstallDirectory` and `EIDE.Toolchain.AnyGcc.ToolPrefix` setting items to setup **Your GCC Compiler** for this project
  ![image](https://user-images.githubusercontent.com/43022536/207522088-7e8cf1a5-6069-478c-8382-74478c1002fd.png)

**Comment by elabdess** [comment]
Thanks for answering!

That helped, I was missing the prefix settings for the GCC based compiler, now it compiles . What about CCRX? it's not GCC based, is ti possible to use as base other toolchain configuration?

bellow is the link to the compiler manual for further information.

https://community-ja.renesas.com/cfs-file/__key/communityserver-discussions-components-files/174/CC_2D00_RX-Compiler-User_2700_s-Manual.pdf

Thanks a lot and great plugin!

**Comment by github0null** [comment]
we not support `CCRX`
