### ISSUE TITLE
[question] How to Run extennsion for IDE in vscode

### ISSUE THREAD

**Issue by BojunZhong** [github0null/eide#196]
I tryed to press F5,But it shows Error
![82ddce2369a11170d4a83ab9473285b](https://user-images.githubusercontent.com/102637083/208368787-9f01edd2-f32d-4c4c-83fc-8d8fde455b2f.png)

**Comment by github0null** [comment]
I can't understand your means.

Please use 'clear and concise description', Tell me what you want to do, and what's happened

**Comment by BojunZhong** [comment]
I want to Run EIDE extensions in Vscode.
![171513a0be862f490ea7da5e64878cb](https://user-images.githubusercontent.com/102637083/208372160-cf262049-5cbd-46b8-aa9f-455515ebaf28.png)

After I click Run And Debug. It will show that
![786f588339a4f36feea49bde0da3bfc](https://user-images.githubusercontent.com/102637083/208372330-072c3997-ca2a-416d-9202-f4172723e761.png)

**Comment by BojunZhong** [comment]
My purpose is not to use EIDE(Just like download from Market). My purpose is to learn its code, how is that works, and Run it.

**Comment by github0null** [comment]
If you want to Debug this extension, you need to do some prepare works, please follow these steps:

- Install NodeJS 14
- Full clone this repo
- Run `npm install` in workspace install all dependences
- Press `ctrl+shift+b`, select `webpack dev` to build extension

After build done, then press F5 start debugger

**Comment by BojunZhong** [comment]
我用的版本是node v14.15.0
前面3步都ok：
Install NodeJS 14
Full clone this repo
Run npm install in workspace install all dependences
到了最后一步
![64bf9eccccdc264b7265f94872e39cf](https://user-images.githubusercontent.com/102637083/208382942-bdd7abcb-0dab-4b55-9a81-7d0399d313e3.jpg)

点击这个npm：webpack
开始报错
![f35a16f8117821698038dde0784ff3c](https://user-images.githubusercontent.com/102637083/208383234-b169c9d2-23c5-4798-be44-128dc5268800.png)

**Comment by github0null** [comment]
- 确保你 clone 了最新的 master 分支，还有其所有的 submodules
- 关于如何开发，调试扩展，请参考官方的教程
