### ISSUE TITLE
再Mac上没有弹出安装编译器的按钮

### ISSUE THREAD

**Issue by BojunZhong** [github0null/eide#197]
我想在mac上使用EIDE，但是他弹出这个找不到编译器的地址，
![801671504707_ pic](https://user-images.githubusercontent.com/102637083/208570635-97128cb8-cdb0-4871-a0ac-6265c7a838cf.jpg)
这个怎么办啊，我该怎么安装啊

**Comment by github0null** [comment]
编译器本来就是要自行安装的，仅为windows平台提供自动安装包

请阅读文档：
https://em-ide.com/zh-cn/docs/getting-started/setup/#%E9%85%8D%E7%BD%AE%E5%B7%A5%E5%85%B7%E9%93%BE
