### ISSUE TITLE
using cmake to generate eclipse project

### ISSUE THREAD

**Issue by Cherish-forever** [github0null/eide#198]
`cmake -G"Eclipse CDT4 - Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug -DBOARD=hpm6750evk ..`
import as eclipse project:
Warning : Project import failed !: Cannot read properties of undefined (reading 'name')

**Comment by github0null** [comment]
请提供导致该错误的 .cproject 文件

---

如果能用 cmake，就应该用 cmake，不需要将项目又导入到这个插件上来
