### ISSUE TITLE
.ept文件如何打开啊

### ISSUE THREAD

**Issue by BojunZhong** [github0null/eide#199]
**What you want to do**
我想要修改输出模板，输出模板在.ept文件里面

**Describe the problem**
.ept文件无法打开

**Expected behavior**
我希望你能够教我打开.ept文件
![1672391142919](https://user-images.githubusercontent.com/102637083/210053240-fd959c31-4132-4057-ab83-86844a614cb7.png)

**Comment by github0null** [comment]
用插件的 新建项目功能 导入
