### ISSUE TITLE
设置Keil C51路径, 出现这个情况, 是什么问题

### ISSUE THREAD

**Issue by GitHub-zzs** [github0null/eide#20]
![image](https://user-images.githubusercontent.com/47681336/72200916-de1fa080-3489-11ea-9b07-fb46e4215fa8.png)

**Comment by github0null** [comment]
这很正常，这表示ARM和C51的路径其中一个还没设置，

如果你不开发stm32，就可以不用设置ARM的路径

**Comment by GitHub-zzs** [comment]
哦, 这么回事啊! 了解了, 多谢.

**Comment by github0null** [comment]
点击下图中的+号可以添加其他的源目录到项目中去
![t](https://user-images.githubusercontent.com/43022536/72232947-64112800-35ff-11ea-8c16-244fb1d54000.png)

**Comment by GitHub-zzs** [comment]
我是这样操作了,但是出现如下提示:
![image](https://user-images.githubusercontent.com/47681336/72245902-853c3d80-362c-11ea-90e5-5c7946ed27d9.png)

**Comment by github0null** [comment]
忘了告诉你了，要添加的目录必须在项目的根目录下，你可以在项目根目录下新建一个文件夹，把要添加的源文件移动到新文件夹下，然后再添加，

**Comment by GitHub-zzs** [comment]
好的,明白了,谢谢!
