### ISSUE TITLE
[question] 我自己写了一个文件夹，想转换成.ept格式，添加到现有的模板里面

### ISSUE THREAD

**Issue by BojunZhong** [github0null/eide#202]
是这样的情况，我自己写了一个模板用以替代EIDE原有的模板，但是我查询源码之后发现模板储存在template文件夹内，包括89c52_sdcc.ept，avr_atmega128_rtos.ept，mcs51.ept。我知道使用EIDE打开这些模板，我的目的是为了写一个自己的模板添加到EIDE里面，但是这些是用.ept格式存储的，我自己已经写好了一个文件夹打算打包成.ept格式，然后添加到Template里面去，请问我该怎么将文件夹转换成.ept文件格式

**Comment by github0null** [comment]
你应该先读一下文档：https://em-ide.com/zh-cn/docs/advance/export_project

**Comment by BojunZhong** [comment]
贼溜，EIDE写的比TI的CCS牛逼多了，牛皮！！！！
