### ISSUE TITLE
【功能请求】 对于A51文件，支持宏高亮与跳转

### ISSUE THREAD

**Issue by NickLiu635** [github0null/eide#208]
A51文件可用的有两种宏
一种是使用C的预编译器，例如 `#define FOUR 4`, 甚至`#include "defs.h"`
还有另外一种
```asm
WRITE_XDATA MACRO dst, val
            mov dptr, #dst
            mov a, #dat
            movx @dptr, a
            ENDM
```

**Comment by github0null** [comment]
这样的功能需要 对应的语法分析工具 分析语法，并实现语言服务，暂时实现不了

目前自带的高亮是针对关键字的，以下就是高亮配置：

https://github.com/github0null/eide/blob/master/lang/a51.tmLanguage.json
