### ISSUE TITLE
JLINK执行文件错误 

### ISSUE THREAD

**Issue by Coolioyang** [github0null/eide#209]
使用了错误的执行文件：
![image](https://user-images.githubusercontent.com/27847846/216852207-0f0d65da-7b2b-4227-8954-634f2f539fe6.png)

**Comment by github0null** [comment]
请先 实用工具 功能中 安装 JLink 软件，或者直接设置一个已存在的 JLink 安装目录，

否则会在环境变量中寻找 JLink.exe

**Comment by Coolioyang** [comment]
找到设置了。多谢。
