### ISSUE TITLE
多个target，生成的hex文件名是projectname，而不是targetname

### ISSUE THREAD

**Issue by MSK202008** [github0null/eide#210]
你好！
![图片](https://user-images.githubusercontent.com/70471630/218239888-4aa5684b-ebd5-4067-9887-d12d729d55fa.png)
这个问题会改进，或者有其他的解决方法吗

**Comment by github0null** [comment]
就是这样的，文件名不包含 targetName，`build/D3` 就是 `D3` target 的编译临时输出目录，D3 就是你的 targetName

如果你要打包或者归档生成的 hex 文件，你可以加入构建后任务，进行重命名
