### ISSUE TITLE
关于EIDE实现反汇编的问题

### ISSUE THREAD

**Issue by BojunZhong** [github0null/eide#212]
我现在想拓展EIDE的功能让EIDE挂载其他编译器以及实现反汇编的功能，但是我仔细查看源码后我发现
![1](https://user-images.githubusercontent.com/102637083/220505883-586fd3f3-52bb-496d-971d-a67b67f6a2aa.png)
这个是用来生成临时文件的，然后我将cmdLine打印出来，在我的电脑上是这样显示的
![2](https://user-images.githubusercontent.com/102637083/220506219-659e1904-0cdb-49c9-a5ee-814095738a1d.png)
也就是生成这个临时文件
![3](https://user-images.githubusercontent.com/102637083/220506325-82620dfa-4d91-41f0-9b00-18c134f90995.png)
但是最后我在电脑上查找这个文件，我发现找不到这个文件
![4](https://user-images.githubusercontent.com/102637083/220506471-62afb156-6011-4f10-9896-6b716401a133.png)
这什么情况啊

**Comment by github0null** [comment]
@BojunZhong 

你往后看几行就知道了，临时文件用完后会被删除

---

要加编译器的话，可以提建议功能点，只要是主流的，免费的编译器，我可以加上

这些代码有的是几年前的，很老了，不调试几遍上来就改肯定会出问题的
