### ISSUE TITLE
最新版的EIDE串口工具栏工具删掉了吗?

### ISSUE THREAD

**Issue by iAoe444** [github0null/eide#218]
看到提交历史中把串口功能删掉了，但是个人觉得这个串口终端的功能很好用，微软的Serial Monitor也用过，但是他没有这个串口终端功能

**Comment by github0null** [comment]
是的，不过 `serial_monitor` 的二进制程序还在，命令行进行了更新，可以在带有 eide 内置环境的终端中使用

![image](https://user-images.githubusercontent.com/43022536/221516798-e35fd4a9-befd-46ee-88a2-800391af99b0.png)

![image](https://user-images.githubusercontent.com/43022536/221512752-dd415707-7429-490b-8500-9d9f5f1177f8.png)

**Comment by iAoe444** [comment]
好的，但是我感觉之前那个加在状态栏的方式挺好的，为什么要删掉，是会有冲突吗

**Comment by github0null** [comment]
原来的状态栏占用太多了，一个功能用了 3 个，给其他插件留的就少了

而且状态栏去交互选 串口，波特率 等参数不太方便

现在官方的串口插件也成熟了，功能也比较齐全，eide 内置的就没必要了
