### ISSUE TITLE
链接时如何增加外部.lib库文件?

### ISSUE THREAD

**Issue by GitHub-zzs** [github0null/eide#22]
我把.lib库文件复制到项目源代码目录下，但是链接时还是没有把该.lib库文件加入链接。该.lib库文件的目录地址也已加入库目录列表中。不知道该如何操作？

**Comment by github0null** [comment]
这个功能因为用的不多，我还没有实现，后续会加上的

**Comment by GitHub-zzs** [comment]
这样啊?那目前有没有什么"曲线救国"的方法呢?

**Comment by github0null** [comment]
你可以在EIDE上编程，然后导出 Keil 项目， 在 Keil 上进行编译

**Comment by github0null** [comment]
这个功能我会尽快加上的

**Comment by github0null** [comment]
v1.1.1版本已经上传，你需要的功能已经加上了
![t](https://user-images.githubusercontent.com/43022536/72323756-6305f680-36e4-11ea-9a8b-2b6fe3bbb8fe.png)
