### ISSUE TITLE
[bug] build error in a 8-bit MCU project with debug option. 

### ISSUE THREAD

**Issue by zhang8083** [github0null/eide#224]
The bug is :
Build error in a 8-bit MCU project with 2 more c files in the condition "enable debug option" and "toolchain SDCC v4.0.1".

I made a 8-bit mcu project. There are three c files in the project, those are main.c, file1.c, file2.c
function func1()  is located in file1.c
function func2() is located in file2.c
function main() is located in main.c
func1() and func2() are called in main()

I enabled the "output debug info" in build option, and build the project.  A link error occurred, the build log is as following:
<img width="546" alt="log1" src="https://user-images.githubusercontent.com/23172659/225219185-931cfc68-fb28-4b1f-b6b1-acfc42ccd3bf.png">

If i disable the "output debug info" in build option, there is no error. The build log is as following:

<img width="463" alt="log2" src="https://user-images.githubusercontent.com/23172659/225219586-67d0da41-1857-4e05-97aa-32caaf4c9e8e.png">

The current sdcc version i used is V4.0.1( for some reason, i must use this customized version)
And I did some experiments. 
1.  I only keep two files, that is file1.c main.c, and move the function func2() into file1.c, then build again, there is no error.
2.  I only relpaced the file "sdas8051.exe" in V4.0.1 with the file in V4.2.0, then build again with the "output debug info" option, there is no error!

I don't know why it happend.
If i enable debug option in eclipse enviroment with the same SDCC version V4.0.1, there is no build error.

**Desktop (please complete the following information):**
 - OS: WIN11
 - EIDE Version: v3.11.1
 - VSCode Version: V1.76.1

**Comment by github0null** [comment]
我在 4.2.0 中测试没有这个问题，应该是你用的第三方版本编译器有 bug

[test_1.zip](https://github.com/github0null/eide/files/10976797/test_1.zip)

为什么 eclipse 没这个问题：

这个插件与 eclipse 唯一不太一样地方就是：**链接流程**，这个插件会将所有除 `main()` (入口点) 之外的 .o 文件打包成 `no_entry_bundled.lib`，然后再与 main.o 链接，eclipse 的方法可能是直接链接所有的 .o

如果你这个版本的在处理带有调试符号的 lib 时有 bug，也许会导致上述问题（猜测）

**Comment by zhang8083** [comment]
感谢您的快速回复！
说明下，V4.0.1虽然是定制版，但是改动很小，不影响编译链接，我用官方版本的V4.0.0存在一样的问题。
你提供的测试代码和我写的差不多，我后来又基于你的代码做了一些在不同环境的测试。

总结所有如下：

Test 1:
SDCC V4.0.1,  EDID：v3.11.1
编译出错，将SDCC V4.2里面的"sdas8051.exe" 替换掉SDCCV4.0里面的相同的文件，编译成功

Test2：
SDCC V4.2,   EDID：v3.11.1
编译成功

Test3：
SDCC V4.0.1,  **EDID: V2.14**
编译成功

除了编译问题，还有另外一个问题：
TEST2 的条件下，生成的cdb文件里面只有 M:main
而Test3条件下，生成的cdb文件里面除了M:main，还有M:foo1和M:foo2. 这种才是正常的。

请参考下我做的测试，帮忙再分析下原因，谢谢。

**Comment by zhang8083** [comment]
另外我对比了 EDID V2.1.14 和最新的V3.11.1的comand line， 会存在比较大的差异

EDID V2.1.14
ASM command line (sdas8051): 
-l -o -s -I.\src

EDID V3.11.1
ASM command line (sdas8051):
-plosgffw -Iinclude -mmcs51 --debug

不清楚和这个问题有没有关联性

**Comment by github0null** [comment]
>
>ASM command line (sdas8051):
>-plosgffw -Iinclude -mmcs51 --debug
>

`-plosgffw` 只影响 .lst 文件内容

```
-p   Disable automatic listing pagination
-l   Create list   file/outfile[.lst]
-o   Create object file/outfile[.rel]
-s   Create symbol file/outfile[.sym]
-g   Undefined symbols made global
-ff  Flag relocatable references by mode in listing file
-w   Wide listing format for symbol table
```

不同点就是 `--debug`，在旧的版本里 asm 没有加 `--debug` (这个是旧版本的 bug)，

剩下的不同的地方就是链接方法的差异，旧版本的就是直接链接所有的 .o, 没有先打包成 .lib

---

cdb 没有参考性，你应该直接看生成的 .sym 和 .asm，只要里面 符号没少 就行

**Comment by zhang8083** [comment]
谢谢。 cdb文件对我很重要，我通过第三方工具debug会解析这个问题，有办法把所有的module都加载进去吗

**Comment by zhang8083** [comment]
谢谢。 cdb文件对我很重要，我通过第三方工具debug会解析这个文件，有办法把所有的module都加载进去吗？

**Comment by zhang8083** [comment]
另外就是有没有办法修改预设的编译或者汇编参数呢？方便调试

**Comment by github0null** [comment]
> 有办法把所有的module都加载进去吗

目前是没有办法的，插件只是只负责调用编译器完成构建流程，不关心生成的产物是否正确

> 另外就是有没有办法修改预设的编译或者汇编参数呢？方便调试

https://em-ide.com/zh-cn/docs/modules/builder#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE

**Comment by zhang8083** [comment]
将所有除 main() (入口点) 之外的 .o 文件打包成 no_entry_bundled.lib，然后再与 main.o 链接。
请问现在改成这种模式的目的是什么呢？为什么不直接链接所有的.o
这样有个问题就是生成的cdb没有其他文件的Module标识，没办法debug。

**Comment by github0null** [comment]
https://sourceforge.net/p/sdcc/discussion/1865/thread/e395ff7a42/#a03e

**Comment by zhang8083** [comment]
请问具体是从哪个版本开始改成这种策略的呢？
能不能做成让用户可以选择这两种模式
如果有debug需求，就只能用旧版本了，不是很方便

**Comment by github0null** [comment]
> 这个一时半会儿改不了，后面我有空可能会加上
> 至于是哪个版本改的，我也记不清了

51 的调试多数都是去用 protues 仿真，把 hex 放进去就行了

奔着 sdcc 去的基本就是因为免费，而且支持c99及以上的语言标准，基本没人玩调试功能

sdcdb/ucsim 我记得之前用过一次，只是模拟器，只能模拟指令，无法触发外部中断，还有闪退 bug

**Comment by zhang8083** [comment]
我们会用到sdcc的debug功能，所以目前比较麻烦，我回溯测试了下
看起来是在3.6.4版本以后调整了链接方式。
能否更新代码实现以下功能：
如果使用debug模式，链接所有的目标文件
如果使用release模式，用目前的链接方式，链接lib和main目标文件。

如果短期内不能实现，能否给些提示，我这边尝试修改代码。
比如需要重点修改哪些文件。

**Comment by github0null** [comment]
改这个功能需要同时改动内置的 unify_builder 和 插件本身

我建议你直接去用 makefile，写起来也快，不必如此麻烦

**Comment by zhang8083** [comment]
不是自己用，就是为了让客户能体验好才用eide的。我先自己研究下，有问题再咨询，谢谢。我先close了
