### ISSUE TITLE
[bug] EIDE导出的keil c51项目，debug时无法显示源文件，只能显示Diassembly的内容

### ISSUE THREAD

**Issue by 123485k** [github0null/eide#228]
**To Reproduce**
1.新建stc15项目
2.导出为导出为keil项目
3.在keil中debug

**Expected behavior**
使用EIDE导出的项目无法在debug模式中设置断点，而使用keil新建的可以
**Screenshots**
![image](https://user-images.githubusercontent.com/45510011/228835592-5f60ca17-9207-441e-b62b-3a8df7444910.png)
eide导出-无法设置断点
![image](https://user-images.githubusercontent.com/45510011/228835775-bd57e06b-6318-4c1f-b25b-e6cb65c22dde.png)
keil新建-可以设置断点

**Desktop (please complete the following information):**
 - EIDE Version: v3.11.2
 - VScode版本
```
版本: 1.76.0 (system setup)
提交: 92da9481c0904c6adfe372c12da3b7748d74bdcb
日期: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
沙盒化: No
```
 - Keil 版本
```
IDE-Version:
μVision V5.24.2.86
Copyright (C) 2017 ARM Ltd and ARM Germany GmbH. All rights reserved.

Tool Version Numbers:
Toolchain:        PK51 Prof. Developers Kit  Version: 9.57.0.0
Toolchain Path:    E:\Keil_v5\C51\BIN
C Compiler:         C51.exe    V9.57.0.0
Assembler:          AX51.exe    V3.15.3.0
Linker/Locator:     LX51.exe    V4.66.87.0
Librarian:             LIBX51.exe    V4.30.1.0
Hex Converter:      OHX51.exe    V1.46.0.0
CPU DLL:               S8051.DLL            V3.113.0.0
Dialog DLL:         DP51.DLL             V2.64.0.0
Target DLL:             STCMON51.DLL         V0, 1, 0, 17
Dialog DLL:         TP51.DLL             V2.60.0.0
```

**Additional context**
some logs, like: `<user_home>/.eide/cl.eide.log`

**Comment by github0null** [comment]
你在 keil 上勾选生成调试信息的选项就行了呀

**Comment by 123485k** [comment]
我勾选了生成调试信息，一样不行

**Comment by github0null** [comment]
所谓的项目本质就是 源文件，头文件，编译参数的集合，导出项目也是导出的这些

只要导出之后编译能够通过，说明上述的这些基本功能没有问题，

无法 debug，说明 IDE 的某些选项没有开启，这些本来就是可选项，你用的 Keil 那就得在上面找到然后开启

不清楚你什么操作的，keil 的相关功能用法你可以去网上找一下
