### ISSUE TITLE
Error : 无效的 Keil ARM 安装路径

### ISSUE THREAD

**Issue by yangbo18416** [github0null/eide#23]
![sp200131_234519](https://user-images.githubusercontent.com/11909282/73552786-d305d200-4483-11ea-9012-033f9fa70903.png)
无论是导入已有的Keil项目(非Cube生成)还是新建项目，都会弹出图片的提示！版本号V1.1.2

**Comment by github0null** [comment]
你好，你需要重新设置keil MDK的安装路径, 打开, 

插件日志在项目目录/.EIDE/log,  截图一下看看

**Comment by yangbo18416** [comment]
你好，问题已解决，我初次使用，未有加载keil tool.ini文件导致了，加载后可以正常编译了！非常感谢！
