### ISSUE TITLE
Multiple errors in buld

### ISSUE THREAD

**Issue by vmwsree** [github0null/eide#232]
I'm running the project on my mac, but a lot of files missing errors are showing, majorly in utils.tz could you help me resolve this

Is there any way to resolve this issue?\n\nAny help would be greatly appreciated. Thank you!

**Comment by github0null** [comment]
Did you followed these steps ?

https://github.com/github0null/eide#how-to-build-

And please show your error messages, i only develop this project on Windows pc.

**Comment by github0null** [comment]
Did you followed these steps ?

https://github.com/github0null/eide#how-to-build-

And please show your error messages, i only develop this project on Windows pc.

**Comment by vmwsree** [comment]
Yes, I have tried running it on Windows also following the steps provided here is the error log. 

https://gist.github.com/vmwsree/1e2dba74d1af6c4a6a3ce6dd2f480c94

**Comment by github0null** [comment]
You need to clone submodules !!!

https://github.com/github0null/eide/tree/master/lib

**Comment by vmwsree** [comment]
Thank you , I have send u an email to connect, please check

also 

`WARNING in ./src/utility.ts
Module not found: Error: Can't resolve './Private/GithubProxy' in '/Users/vmwsree/ASH/eide/src'
 @ ./src/utility.ts
 @ ./src/extension.ts

WARNING in ./src/extension.ts
Module not found: Error: Can't resolve './Private/TelemetryTask' in '/Users/vmwsree/ASH/eide/src'
 @ ./src/extension.ts
`
hope these warnings are expected

**Comment by github0null** [comment]
Ignore these warnings, they are inessential

```
Can't resolve './Private/GithubProxy' 
Can't resolve './Private/TelemetryTask'
```
