### ISSUE TITLE
[question] 关于 Side bar 的交互问题

### ISSUE THREAD

**Issue by eatradish** [github0null/eide#236]
我现在按照文档的建议，把 EIDE 的 Side bar 放到了右边，但是我发现有时候 vscode 启动并不会显示 EIDE Side bar，仔细一看发现是 VSCode 不知道为什么收起来了：

![image](https://user-images.githubusercontent.com/19554922/232974038-4d7d6ee3-da38-4cbb-a806-b035b31454fc.png)

这里选择 "Secondary Side bar" 就好了。但如果用户没发现这个选项，就会以为 EIDE 是自己坏了，所以我在想着能不能在 `editor/title` 这个地方加一个打开 EIDE Side bar 的选项，只是后面翻了下 VSCode 的插件 API，发现好像我的想法是不可实现的

不知道作者有什么好的解决方案？

**Comment by github0null** [comment]
有按钮可以用来打开侧边辅助栏，这是最快捷的方法

![image](https://user-images.githubusercontent.com/43022536/232982912-bb18b8ee-d586-46d6-9647-3e271f37ef56.png)

ui 的容器是共享的，用户可能将其它插件的 ui 也放置到里面，加这样的选择 `打开 EIDE Side bar 的选项` 并不合适
