### ISSUE TITLE
Is it possible to add support for running unit tests?

### ISSUE THREAD

**Issue by DanVedDavia** [github0null/eide#240]
I would like to be able to run unit tests using a test framework, similar to how it can be done in PlatformIO.

In the current version, the only "actions" are: build, clean, program and rebuild. I would like to have one additional action called "test".

There should be separate configurations for testing, like which folders to include, what framework to use etc.

Other than this issue, I am loving the extension!

**Comment by github0null** [comment]
This extension is a frameless development tool that is suitable for compiling bare source code.

I don't know what a unit test does, compile the test code ?

If this feature is not clear, and there are no clear rules and paradigms, I can't implement it !
