### ISSUE TITLE
[bug] IAR project compile issue

### ISSUE THREAD

**Issue by bupleurum** [github0null/eide#241]
**What are you doing?**
Import IAR project and use IAR compiler to compile the project.

**Describe the bug**
After importing a IAR project, use IAR compiler to compile the project, eide reports an error, looks like it relates to .s asm file.

**To Reproduce**
1. Import IAR project (NXP LPC55S69 IAR project generated by NXP Config Tool, the project can be compiled by using IAR directly)
2. Click on 'Build' or 'Rebuild'

**Expected behavior**
The project should be compiled successfully.

**Screenshots**
<img width="328" alt="eide_asm_error" src="https://user-images.githubusercontent.com/28855549/236370270-6cc211af-1254-4cc7-b638-3fee70ce6a4b.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - EIDE Version [v3.12.0]
 - VSCode Version [v1.78.0]
 - IAR Version [v9.32.2]

**Comment by github0null** [comment]
fixed in `v3.12.2023051401`
