### ISSUE TITLE
I got this issue,but i don't konw how to fix it.i compile this project below keil,it works well.

### ISSUE THREAD

**Issue by majorzpley** [github0null/eide#247]
>> [ 14%] CC '../Drivers/ADXL345/Src/bakhandle.c'
"../Drivers/ADXL345/Inc/double_integral.h", line 29: Error:  #5: cannot open source input file "arm_math.h": No such file or directory      
  #include "arm_math.h"
//stm32f4xx DSP库，带FPU，硬件加速FFT

**Comment by github0null** [comment]
自己下载下来，放到项目里

https://github.com/ARM-software/CMSIS-DSP/tree/main/Include
