### ISSUE TITLE
[bug] device DFP from repo is lagging behind 

### ISSUE THREAD

**Issue by hiddenblue** [github0null/eide#255]
**What are you doing?**
Tell us what you were doing when the bug occurred.

the version of  GD32 DFP (series devices and support  and example  ) from repo is lagging behind that from gd32 office website and keil5。

我发现eide提供的dfp from repo下载的版本比gd32官网或者keil内置的要老一些，比如gd32f4xx series 会没有新出的f470，只有450的。
可能repo提供的需要稍微更新一下，或者让我们自己去下载dfp也行

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 xxx]
 - EIDE Version [e.g. v3.8.3]
 - VSCode Version [e.g. v1.68.1]

**Additional context**
some logs, like: `<user_home>/.eide/cl.eide.log`

**Comment by github0null** [comment]
插件是支持直接安装 pack 包的，可以从磁盘上选

也可以将 pack 文件提交到 https://github.com/github0null/eide-cmsis-pack
