### ISSUE TITLE
[bug] vscode安装eide失败，可能是vscode 64位的不支持

### ISSUE THREAD

**Issue by wagshiwei** [github0null/eide#257]
vscode安装eide插件失败，可能是vscode 64位的不支持
<img width="337" alt="image" src="https://github.com/github0null/eide/assets/20392885/7193009e-7b64-4520-924c-4b634cbacea1">

**Comment by github0null** [comment]
网络原因，插件是要在线安装的

**Comment by wagshiwei** [comment]
下了32位vscode试了，32位可以安装成功，那个visx package windows下为什么只提供32位

**Comment by github0null** [comment]
插件本来就是 64 位的，现在谁还用 32 位系统啊

![image](https://github.com/github0null/eide/assets/43022536/0cbf7957-33f2-4d27-a7a0-a9039a57a91f)

> 那个visx package windows下为什么只提供32位

后缀里的 win32 只是操作系统标识，不是指 32 位
