### ISSUE TITLE
WINDOWS目录带空格导致无法编译。。。。。

### ISSUE THREAD

**Issue by YukawaMi** [github0null/eide#26]
keil安装在 D:\Program Files (x86)\  目录下，编译时会由于目录名中的空格出现找不到路径的问题，不知道这个问题能解决吗

**Comment by github0null** [comment]
发张出现问题的截图看看

**Comment by YukawaMi** [comment]
哇，响应这么快，我印象中我以前powershell解决这个问题是用变量来定义这些带空格的路径来结局的，要不你试试？PS1脚本先用变量定义目录，然后执行的时候命令是调用的变量
https://ibb.co/X4Mf28S
https://ibb.co/k13gZ3Z

**Comment by github0null** [comment]
这是 CMD 的问题，但对于 CMD 的路径空格，我已经做过处理了。
这个问题会想办法解决的

**Comment by github0null** [comment]
v1.7.0 昨日已更，应该没问题了

**Comment by YukawaMi** [comment]
OK，测试了，没有问题了
