### ISSUE TITLE
[question] 有没有考虑过支持原版的clang

### ISSUE THREAD

**Issue by yyjdelete** [github0null/eide#260]
https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm
偶然发现arm还维护了这么一个编译器, 感觉像是armclang对应的开源免费版本, 但好像部分参数又和AC6不一样， 我试过选AC6，然后把编译器exe的名字改了也跑不起来

**Comment by github0null** [comment]
用过几次，单从生成的代码大小来看，llvm 的生成的不如 gcc 简洁，而且用的人太少了，

后面可能会增加支持，但近期不会

**Comment by yyjdelete** [comment]
嗯，我其实也只是因为看网上说llvm的优化要好一些，想试试看llvm编译出来到底啥区别
