### ISSUE TITLE
[question] Error due to path

### ISSUE THREAD

**Issue by SynonZelra** [github0null/eide#265]
**What you want to do**
Dev on CH582

**Describe the problem**
New Project -> Remote Respo. -> WCH -> CH582 -> random name -> build

`/bin/bash: -c: line 1: unexpected EOF while looking for matching `
`/bin/bash: -c: line 2: syntax error: unexpected end of file`

**Expected behavior**
just compile

**Update**
Now I think I found the root cause, it's about path, that I can't have the ' symbol in projects.

this path works fine
`/mnt/project/Toms_Project`

this path leads to the problem error
`/mnt/project/Tom's_Project`

**Comment by SynonZelra** [comment]
Sry I need more test

**Comment by github0null** [comment]
You can not use these Special symbols: '{,},(,),&,|,...' in filename or path

because these symbols will be interpreted as part of the command, will cause a commandline error
