### ISSUE TITLE
[question] 鼠标悬停在函数出现中文乱码，但是打开源文件不会出现乱码

### ISSUE THREAD

**Issue by spark-boy** [github0null/eide#268]
![问题](https://github.com/github0null/eide/assets/78426711/2f12c5ea-ca2d-45b0-8b20-9126c0801e2f)
![2](https://github.com/github0null/eide/assets/78426711/9edfe8e4-db62-46f4-a7ee-757e1e3a3214)

**Comment by stars-under** [comment]
这个应该是你文件以GBK形式保存的,C/C++插件默认是UTF-8打开的.改下保存的格式
