### ISSUE TITLE
在VSCode里面安装不了

### ISSUE THREAD

**Issue by VampireMao** [github0null/eide#270]
我先在VSCode里面安装，直接报错。我甚至把梯子开成全局代理也是同样的结果。
![image](https://github.com/github0null/eide/assets/26102623/1ce5f7c3-f6b9-4c21-a5d9-64d2d868766f)

然后我再下载vsix包进行安装，它确往我的vs2022里面装，当然肯定也失败了。
![image](https://github.com/github0null/eide/assets/26102623/631683bc-9c3f-432e-b2ee-cf26fed96f92)

**Comment by github0null** [comment]
![image](https://github.com/github0null/eide/assets/43022536/7d036c98-09ef-4888-996a-ca915a7e0e79)

如何安装 vsix，参考文档：

https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions
