### ISSUE TITLE
[bug] 在macOS下使用时编译二进制格式问题（转载论坛中讨论的问题）

### ISSUE THREAD

**Issue by Qing201** [github0null/eide#273]
使用环境

操作系统版本：MacOS Ventura 13.4
操作系统平台(x86/x64)：arm64
VsCode 版本：1.79.1
EIDE 插件版本：v3.13.2023060401，从v3.10.11(不含)之后的所有版本都不行
C/C++ 插件版本：v1.15.4
何种编译器(keil_c51/sdcc/armcc5/armgcc/...)：sdcc
编译器版本(非编译问题可忽略)：sdcc 4.2.0 #13081
描述问题

正在文件夹 STC8A.TEST 中执行任务: unify_builder -p /Users/zhangqi/Projects/MCS-51/STC8A.TEST/build/Debug/builder.params

从3.10.11升上来之后，就无法生成hex或bin了
，甚至整个build/Debug目录也只生成了builder.params和unify_builder.log两个文件，并且unify_builder.log是空的。控制台最多只输出上面那一段话，就像是完全没有调用sdcc一样

屏幕截图
![image](https://github.com/github0null/eide/assets/72839112/a1189bfa-633c-41c5-a7ae-1d3aa14227e2)

转载论坛链接：https://discuss.em-ide.com/d/533-v31011hex/4

**Comment by github0null** [comment]
新版本应该已经修复了，有时间可以再试试
