### ISSUE TITLE
[bug] 在切换构建配置时上一次的设置丢失

### ISSUE THREAD

**Issue by dukmu** [github0null/eide#276]
**What are you doing?**
使用EIDE构建STM32G4工程

**Describe the bug**
设置好GCC编译配置后切换到ARMC编译，再切换回GCC，链接脚本路径选项又回到了初始值
这个配置应该可以像{project}.arm.options.gcc.json一样保存，方便调试

**To Reproduce**
首先使用CubeMX初始化Keil工程和Makefile工程，
然后用EIDE导入Keil工程，使用ARMC编译通过，
切换到GCC编译，设置好startup和链接脚本路径，编译通过
然后切换回ARMC，再切换回GCC，链接脚本路径回到了初始值

**Screenshots**
![屏幕截图 2023-07-28 170819](https://github.com/github0null/eide/assets/74289192/acb656f4-9df3-41d0-b5c9-0527cf5ae05b)
![image](https://github.com/github0null/eide/assets/74289192/f6c9815b-3a0b-4c2b-9f38-91bd60b76df9)

 - OS: [Windows 10 Pro]
 - EIDE Version [v3.13]
 - VSCode Version [v1.80.0]

**Comment by github0null** [comment]
应该使用新建 target 来保存不同的编译配置，对于同一个 target，是不会保存上一次的配置的

https://em-ide.com/docs/advance/project_targets#switch-target
