### ISSUE TITLE
[bug] iasmarm 有-n 选项，编译报错 

### ISSUE THREAD

**Issue by jht-cool** [github0null/eide#277]
compilation failed at : 
"..\Middlewares\Third_Party\FreeRTOS\Source\portable\IAR\ARM_CM0\portasm.s", exit code: 3
command: 
  "d:\IAR9\arm\bin\iasmarm.exe" -S --thumb -w+ -l .\build\DT630_V1\__\__\Middlewares\Third_Party\FreeRTOS\Source\portable\IAR\ARM_CM0\portasm.lst --cpu Cortex-M0 --endian little -r -s+ -n -o .\build\DT630_V1\__\__\Middlewares\Third_Party\FreeRTOS\Source\portable\IAR\ARM_CM0\portasm.o .\..\..\Middlewares\Third_Party\FreeRTOS\Source\portable\IAR\ARM_CM0\portasm.s
   at unify_builder.Program.Main(String[] args_)
---
Error in command line option '-n': No such option

**Desktop (please complete the following information):**
 - OS: Windows 10
 - EIDE Version[v3.13.2023060401
 - VSCode Version 1.81.1

**Additional context**
some logs, like: `<user_home>/.eide/cl.eide.log`

**Comment by github0null** [comment]
检查一下这个选项，如果 勾选了 就会有 -n

![image](https://github.com/github0null/eide/assets/43022536/9783a5b2-435c-4ea7-9987-8ebe89b5b8ae)
