### ISSUE TITLE
[bug] The name of library is incorrect.

### ISSUE THREAD

**Issue by ShiinaKaze** [github0null/eide#282]
**What are you doing?**
Creating a new project.

**Describe the bug**
The name of library is incorrect.
The name of the library should be SPL instead of HAL.

**To Reproduce**
1. Go to 'Activity Bar'
2. Click on 'EIDE'
3. Click on 'OPERATION-New Project'
4. Select 'Internal Template'
5. Choose 'STM32F1 GCC Quickstarts'

**Expected behavior**
The name of library is incorrect.

**Screenshots**
![image](https://github.com/github0null/eide/assets/89641145/1c7bdbcd-ea2b-478b-9c29-9bfb9457f5ec)

**Desktop:**
 - OS: [Windows 11 pro]
 - EIDE Version [v3.13.2023060401]
 - VSCode Version [v1.81.1]

**Additional context**
none

**Comment by github0null** [comment]
这个名字定义问题你可以自行修改，每个人有自己的叫法
