### ISSUE TITLE
有没有办法设置外部终端为debugger console或者更新下debug console让其能自动补全

### ISSUE THREAD

**Issue by Tracker647** [github0null/eide#286]
现在扩展debug只能在vscode内部的debug console与gdb交互，而且这个debug console是没法tab自动补全的，很不方便，直接用JLink自带的gdb server原始调试又看不到rtos线程情况，在launch.json或者扩展设置里面好像也没有设置外部终端为debug console的情况，有没有一个两全的方法让vscode上debug既能用到外部终端，或者debug console能够实现上外部终端应有的功能，又能看freeRTOS线程的情况？

**Comment by github0null** [comment]
我没有这样用过，调试器部分，你可以去 Cortex-debug issue 里问一下，
