### ISSUE TITLE
[bug] cube生成的工程导入之后无法进行结构体跳转以及自动补全

### ISSUE THREAD

**Issue by Anveil** [github0null/eide#288]
芯片型号是stm32f107vc，能够编译通过。
似乎是没能找到对应的宏定义。
![image](https://github.com/github0null/eide/assets/58169392/2ddac0a9-d761-48b2-8f7b-2ba81aa1df25)
![image](https://github.com/github0null/eide/assets/58169392/54830198-1368-4006-9c50-383c04b1b07d)

**Comment by github0null** [comment]
跳转，自动补全 不是本插件提供的功能
