### ISSUE TITLE
[bug] 内置Perl版本过低，会与LaTeX 需要的版本冲突

### ISSUE THREAD

**Issue by ganyuanzhen** [github0null/eide#292]
**What are you doing?**
Tell us what you were doing when the bug occurred.
当同时启用EIDE 与 LaTeX Workshop 时，在编写LaTeX文档后，使用latexmk 编译会使用EIDE的内置perl。由于EIDE内置的perl版本过低，会导致latexmk编译失败。因此需要关闭EIDE，十分麻烦。
**Describe the bug**
由于EIDE内置的perl版本过低，会导致latexmk编译失败。因此需要关闭EIDE，十分麻烦。
**To Reproduce**
1. 同时安装EIDE 和 latex workshop
2. 编写latex文档
3. 使用latexmk方式编译文档
4. 报错
**Expected behavior**

**Screenshots**
```
File::Path version 2.08 required--this is only version 1.08 at D:/Users/15228/AppData/Local/Programs/MiKTeX/scripts/latexmk/latexmk.pl line 75.
BEGIN failed--compilation aborted at D:/Users/15228/AppData/Local/Programs/MiKTeX/scripts/latexmk/latexmk.pl line 75.
```

当disable EIDE 后，不再报错。
```
Reverting Windows console CPs to (in,out) = (936,65001)
Initial Win CP for (console input, console output, system): (CP936, CP65001, CP936)
I changed them all to CP936
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 4 Apr. 2023. Version 4.80.
Latexmk: Nothing to do for 'template.tex'.
Latexmk: All targets (template.pdf) are up-to-date
```

**Desktop (please complete the following information):**
 - OS: Windows 11 10.0.25967
 - EIDE Version v3.13.2023061101
 - VSCode Version v1.82.1

**Additional context**
some logs, like: `<user_home>/.eide/cl.eide.log`

**Comment by ganyuanzhen** [comment]
希望能更新一下perl版本(●ˇ∀ˇ●)

**Comment by github0null** [comment]
这个 perl 是 msys1 里的程序。由于msys1好像没有更新了，因此暂时更新不了
