### ISSUE TITLE
[question] Add "c++17" selection

### ISSUE THREAD

**Issue by qianchen36** [github0null/eide#293]
**What you want to do**
I wanna use c++17 features while building the project

**Describe the problem**
The newest selection in the list was just "c++14"
Arm Complier 6 was already support c++17
<img width="245" alt="image" src="https://github.com/github0null/eide/assets/62316012/69216558-9f95-4c57-9eda-e4e120019ae7">

**Expected behavior**
The list may have a "c++17" selection

**Comment by github0null** [comment]
You can add compiler options to override it

https://developer.arm.com/documentation/101754/0621/armclang-Reference/armclang-Command-line-Options/-std

For example:

`-std=c++17`

![image](https://github.com/github0null/eide/assets/43022536/f82822dc-c876-42f2-8f4a-045274784996)
