### ISSUE TITLE
[question]  CMSIS Configuration Wizard 代码有一部分没有开源？

### ISSUE THREAD

**Issue by hongshui3000** [github0null/eide#296]
/res/html/cmsis_wizard_view
目录下的代码不是开源的？ 看上去都是编译后的代码

我正在寻找kconfig gui的参考代码才会有这个疑问（找个参考重新写一下）
类似这个插件https://nrfconnect.github.io/vscode-nrf-connect/reference/ui_kconfig.html

**Comment by github0null** [comment]
这个路径的存放的是 前端界面，是打包后的，

解析器在这：https://github.com/github0null/eide/blob/master/src/CmsisConfigParser.ts

https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/configWizard.html

这个跟 kconfig 是完全不一样的格式

**Comment by hongshui3000** [comment]
理解了，本身我就需要重写解析器和前端界面。谢谢

**Comment by github0null** [comment]
前端页面的源码压缩包，如果你还需要的话：

[cmsis_config_wizard-master.tar.gz](https://github.com/github0null/eide/files/13748799/cmsis_config_wizard-master.tar.gz)

**Comment by hongshui3000** [comment]
非常感谢大佬
