### ISSUE TITLE
Where to define Off-Chip XData Memory

### ISSUE THREAD

**Issue by cptpiepmatz** [github0null/eide#300]
**What you want to do**
Using µVision I can define the start and size of external memory.
![image](https://github.com/github0null/eide/assets/3590829/45a7cc6a-2cbc-4b0f-be9d-8ada25837907)
Does eide have any way to also define this value?

**Describe the problem**
I want to define my external memory as I'm using one. I cannot find a setting for it and it seems that importing a `.uvproj` disgards that setting.

**Expected behavior**
Let me define my external memory or show me where that config rests.

**Comment by github0null** [comment]
We not have gui settings, so you can only use the raw compiler params

Here's a reference, maybe you need a google translator
https://github.com/github0null/eide/issues/143

KeilC51 LX51 Guide:
https://developer.arm.com/documentation/101655/0961/LX51-User-s-Guide/Linking-Programs
