### ISSUE TITLE
[bug] Error can't connect WCH Template 

### ISSUE THREAD

**Issue by Witawat** [github0null/eide#302]
![image](https://github.com/github0null/eide/assets/4926369/45efe68c-b9af-46a6-9839-8e07b04eb3e3)

**Comment by github0null** [comment]
we fixed

please try it again

**Comment by Witawat** [comment]
> we fixed
> 
> please try it again

![image](https://github.com/github0null/eide/assets/4926369/7e58caef-0984-435d-a336-bcb5cd737db1)

**Comment by github0null** [comment]
这个错误可以忽略
