### ISSUE TITLE
Cannot read properties of undefined (reading 'C51')

### ISSUE THREAD

**Issue by Aven-code** [github0null/eide#304]
![image](https://github.com/github0null/eide/assets/51937497/bce9b5ad-55aa-4e01-9c84-e8502cd3de24)

**Comment by Aven-code** [comment]
EIDE插件只支持 keil5 程序吗？

**Comment by github0null** [comment]
> EIDE插件只支持 keil5 程序吗？

是的，只支持 keil5 的导入；不支持 keil4
