### ISSUE TITLE
armclang汇编器支持ARM语法

### ISSUE THREAD

**Issue by Deadline039** [github0null/eide#308]
keil安装AC6.21后armclang可以选择ARM语法，eide里armclang只能选GNU语法，希望能支持一下
![PixPin_2024-01-24_21-09-48](https://github.com/github0null/eide/assets/91746341/f4f1b31b-55aa-4040-908c-e37f5ebb3bfc)

**Comment by github0null** [comment]
此处有相关解答：

https://discuss.em-ide.com/d/501-keil-ac6/9
