### ISSUE TITLE
[bug] 无法正确识别linux下的gcc编译链位置

### ISSUE THREAD

**Issue by AyahaShirane** [github0null/eide#309]
EIDE.ARM.GCC.Install Director 无法适应linux环境下的安装路径, 我将其设置为/bin/，其自动补全为/bin/bin 并提示无法找到编译器gcc的安装位置

`无法找到编译器 'GCC' 的安装位置 ！, [path]: '/bin/bin'`

**Comment by github0null** [comment]
linux 上一般不需要设置这个路径，只要你确保打开 shell 执行 arm-none-eabi-gcc 命令，命令有效就行

你只需设置 EIDE.ARM.GCC.Prefix 设置项

插件会自动找到路径

===

如果你的 gcc 被安装到一个自定义的路径，你才需要设置 EIDE.ARM.GCC.InstallDirectory 这个设置项
