### ISSUE TITLE
能持支生成compiledb.json吗？

### ISSUE THREAD

**Issue by liangz678** [github0null/eide#311]
能持支生成compiledb.json吗？我希望生成compiledb 以便在nvim中有代码提示和补全功能。

**Comment by github0null** [comment]
目前支持编译后在 build/Debug 目录下生成 [compile_commands.json](https://clang.llvm.org/docs/JSONCompilationDatabase.html)

不确定是不是你要的，

**Comment by DYAAL** [comment]
> 目前支持编译后在 build/Debug 目录下生成 [compile_commands.json](https://clang.llvm.org/docs/JSONCompilationDatabase.html)
> 
> 不确定是不是你要的，
I'm curious about how to generate compile_commands.json. What configurations are needed? I want to use my Clang plugin for code completion.
