### ISSUE TITLE
 About how to reload the project in the IDE:[bug] 

### ISSUE THREAD

**Issue by DYAAL** [github0null/eide#314]
This is a very useful plugin, but I encountered a small issue while using it.
Firstly, for example, if I regenerate the code in CubeMX, how can I reload it in the IDE? Or do I have to re-import the project in the IDE to apply the changes?

Secondly, it seems that the configuration of project resources in the IDE is not saved. For instance, after regenerating with CubeMX, the previously configured resource settings get overwritten. Is there a way to avoid this issue?

**Comment by github0null** [comment]
Not have 'reload' feature.

The project import feature is a one-off operation.

Docs: https://em-ide.com/en/docs/getting-started/import_prj/

If you want to generate code by cubemx, you need add source files and configs manually in eide project.

**Comment by github0null** [comment]
> If possible, it would be great to have a feature in the IDE that allows saving configuration information for project compilation, such as adding header files.

These features already exist

1. this IDE have `auto-save` feature. you don't need to save project manually (If you want to do so, we also have a save button)
    ![image](https://github.com/github0null/eide/assets/43022536/073f46e3-61f2-4b46-ae15-5972c20de2f1)

3. about how to 'adding header files.' -> https://em-ide.com/en/docs/modules/project_attr#include-directories
