### ISSUE TITLE
我想请问一下插件如何支持散列文件呢？[question] 

### ISSUE THREAD

**Issue by DYAAL** [github0null/eide#319]
**What you want to do**
A clear and concise description of what you want to do.
我想请问一下插件如何支持散列文件呢？
**Describe the problem**

**Expected behavior**

**Comment by github0null** [comment]
什么是散列文件？

**Comment by DYAAL** [comment]
> 什么是散列文件？

请问一下方便留个v吗，我发给你看看。。
散列文件就是编写程序时候的link file， 比如：
![1711694784476](https://github.com/github0null/eide/assets/126035353/ed86be09-5e71-412a-aa05-287b8fd660e0)
在keil里面是通过下面这个地方去指定的，散列文件可以指示编译器去把链接文件按照要求去把变量的绝对地址放到文件要求的地方去。

![1711694833488](https://github.com/github0null/eide/assets/126035353/ab210dc3-5be5-429b-8bf3-c58ab7380d5d)

**Comment by github0null** [comment]
选一下这两个设置就行了

 - `Use Custom Linker Script File` 选 true
 - `Linker Script File Path` 填文件路径

在 Keil 里这个文件叫法就是 Scatter File

https://em-ide.com/docs/modules/builder

![image](https://github.com/github0null/eide/assets/43022536/7f5fed19-7aaf-49b3-9f16-0501e454eae1)

**Comment by DYAAL** [comment]
okok非常感谢，再次感谢为这么好用的工具做了那么多工作

**Comment by DYAAL** [comment]
> 选一下这两个设置就行了
> 
> * `Use Custom Linker Script File` 选 true
> * `Linker Script File Path` 填文件路径
> 
> 在 Keil 里这个文件叫法就是 Scatter File
> 
> https://em-ide.com/docs/modules/builder
> 
> ![image](https://private-user-images.githubusercontent.com/43022536/317977745-7f5fed19-7aaf-49b3-9f16-0501e454eae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTU3NzUsIm5iZiI6MTcxMTY5NTQ3NSwicGF0aCI6Ii80MzAyMjUzNi8zMTc5Nzc3NDUtN2Y1ZmVkMTktN2FhZi00OWIzLTlmMTYtMDUwMWU0NTRlYWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA2NTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NzU2MDgxZDQxMzRkYmI3NmUxMThhZDc5ZWZkZGI2YzczMWQzYzdlNzc2ZDEzMTAzZjk5NDk0ZjQwNmMyMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iEWF0ccqYRBEXHAEnFrhrNBcUX93az_p0sdYblyn67Y)

好像是因为我的ide不知道为啥变成中文了。。导致我找不到。。它翻译为链接脚本了。。我一直都叫的散列文件。。再次感谢
