### ISSUE TITLE
c_cpp_properties.json is modified when replacing project folder 

### ISSUE THREAD

**Issue by ghosoft** [github0null/eide#32]
![image](https://user-images.githubusercontent.com/4844538/81459732-f1424300-91d3-11ea-9dc2-b26bd140ea85.png)
![image](https://user-images.githubusercontent.com/4844538/81459744-facbab00-91d3-11ea-90e7-3fb45dd29ac3.png)

Would it be better to use relative paths

**Comment by github0null** [comment]
以后将会作出改进，c++插件的 win32 配置由 eide 控制，任何手动的更改都将会被覆盖
