### ISSUE TITLE
jlink烧录stm32系列的指令异常

### ISSUE THREAD

**Issue by wlyhrog** [github0null/eide#320]
我在使用edie编译代码后第一次烧录正常，但是往后的烧录程序使用jlink烧录时重复烧录老是报错，但是自己编写bat脚本直接烧录没有此问题，我想eide插件自己提供的下载指令应该有缺失，所以希望你们后续能提供一个jlink下载的cmd命令钩子，我自己将需要的指令填写到里面，可以通过下载按钮直接下载，就像你们提供的构建配置中的构建选项一个可以加载自己的bat或者其他指令去执行

**Comment by github0null** [comment]
https://discuss.em-ide.com/d/675-eide-jlink/14
