### ISSUE TITLE
请问一下插件可以让支持生成cmake文件吗，类似于clion那样的功能？[question] 

### ISSUE THREAD

**Issue by DYAAL** [github0null/eide#326]
请问一下插件可以让支持生成cmake文件吗，类似于clion那样的功能？
除此以外我想知道能不能支持用arm-cc工具链或者自己指定工具链编译，最好是能根据项目自己生成cmake，增加这个功能会让使用者自由很多

**Comment by github0null** [comment]
暂不支持生成 CMakeList.txt，后面会添加到计划里的

**Comment by DYAAL** [comment]
> 暂不支持生成 CMakeList.txt，后面会添加到计划里的

okok，感谢解答
