### ISSUE TITLE
[question] pyocd烧写时不支持指定远程probe

### ISSUE THREAD

**Issue by nocodo189753** [github0null/eide#327]
**What you want to do**
 pyocd烧写时不支持指定远程probe

**Describe the problem**
pyocd支持以下方式
本地机接probe连target，运行`pyocd server --allow-remote`
远程编译服务器直接烧写`pyocd load --uid=remote:IP:ADDR ...`
pyocd 的config文件只能设置option，不能指定probe，EIDE的UI中没有设置probe（--uid）的入口

**Expected behavior**
在EIDE中添加相关入口

**Comment by github0null** [comment]
已经在 v3.17.2 pre-release 版本中增加了附加命令行选项，用于增加自定义的命令

![image](https://github.com/github0null/eide/assets/43022536/ff12dc2a-db4d-47ba-abc8-b11c6e76968e)
