### ISSUE TITLE
选择CPU类型为：Cortex-M33.Dsp时，没有硬件浮点选项的配置

### ISSUE THREAD

**Issue by ckforce** [github0null/eide#328]
目前是的情况是选了Cortex-M33可以选FPU类型
![image](https://github.com/github0null/eide/assets/22431888/d10903b5-fe80-483e-ada7-736eb1c8ff74)

选择Cortex-M33.Dsp，就没法选择FPU类型了
![image](https://github.com/github0null/eide/assets/22431888/b5f23925-e6ce-4339-a677-e829f8f19513)

并且选择Cortex-M33.DSP时，编译参数输出的是-mfloat-abi=soft

需要在选择M33.DSP的情况下启用硬件FPU

**Comment by github0null** [comment]
该问题已在 v3.16.1 中修复
