### ISSUE TITLE
Could not detect CPU clock speed

### ISSUE THREAD

**Issue by wangwenyue** [github0null/eide#33]
![QQ截图20200519094123](https://user-images.githubusercontent.com/15112619/82275464-6fad9a80-99b5-11ea-95bd-419df3a362fa.png)
![image](https://user-images.githubusercontent.com/15112619/82275606-c3b87f00-99b5-11ea-9b23-89a560438c4a.png)

这个是指 CPU 晶振的频率吗？在 keil 里面看到是 12MHz，这个在eide里面是需要在哪配置一下吗？

谢谢

**Comment by wangwenyue** [comment]
用 GUI 下载模式暂时解决问题，期望可以后续优化

**Comment by github0null** [comment]
出现 Could not detect CPU clock speed 的原因比较复杂，但大多都是板子连接不稳定所致；
这些运行输出都是来自 JFlash.exe，EIDE 只是负责发送一些命令；
