### ISSUE TITLE
cortex-debug配置文件的自动生成为什么没了

### ISSUE THREAD

**Issue by dongda-villager** [github0null/eide#333]
![image](https://github.com/github0null/eide/assets/83150925/69765d7f-86d8-4d9c-a192-6ecde9d4047f)
如图，为什么新版本自动生成没了

**Comment by github0null** [comment]
这个功能会覆盖用户自己编辑的 launch.json

该功能现已被转移到右键菜单中，改为手动执行

https://discuss.em-ide.com/d/684-316launchjson/2
