### ISSUE TITLE
[question] compile *.c files with g++

### ISSUE THREAD

**Issue by AndreyShi** [github0null/eide#335]
**What you want to do**
I want chose compiler gcc or g++ for compile one file in project

**Describe the problem**
i dont find where  i can chose compiler g++ or gcc  for source file in project

**Expected behavior**
compile other *.c and *.cpp files with autochosen compiler and one file main.c compiled with g++

**Comment by AndreyShi** [comment]
i found solution here https://github.com/github0null/eide/discussions/289

**Comment by github0null** [comment]
it will auto detect
- gcc for *.c files
- g++ for *.cpp, *.c++, *.cc files

If you want to use g++, you need rename your `main.c` to `main.cpp`
