### ISSUE TITLE
有没有办法实现.s文件的代码联想

### ISSUE THREAD

**Issue by 5ROLLFE** [github0null/eide#336]
**What you want to do**
A clear and concise description of what you want to do.
我想要在我声明中断函数时，vscode会根据我的prompt联想startup.s文件中对应的中断函数名称
**Describe the problem**
vscode不能识别到startup.s文件的内容，无法提供关键词联想
**Expected behavior**
有没有什么办法可以实现intelligence识别.s文件，从而提供关键词联想

**Comment by github0null** [comment]
自己做插件实现，你想干啥都行

**Comment by 5ROLLFE** [comment]
我要怎么实现这种效果呢，如果需要做插件的话

**Comment by github0null** [comment]
去看 vscode 文档，自动补全功能 部分
