### ISSUE TITLE
[bug] /home/xy/.vscode/extensions/cl.eide-3.17.0/res/tools/linux/unify_builder/unify_builder: Permission denied

### ISSUE THREAD

**Issue by MirTITH** [github0null/eide#339]
**What are you doing?**

Build my project after upgraded to EIDE 3.17.0.

**Describe the bug**
I got permission error when building.

```shell
/bin/bash: 行 1: /home/xy/.vscode/extensions/cl.eide-3.17.0/res/tools/linux/unify_builder/unify_builder: 权限不够

 *  终端进程“/bin/bash '-c', 'unify_builder -p /home/xy/Documents/Embedded/eide_template/build/Debug/builder.params'”启动失败(退出代码: 126)。 
 *  终端将被任务重用，按任意键关闭。
```

**To Reproduce**
Just click the build button.

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux 24.0]
 - EIDE Version [v 3.17.0]
 - VSCode Version [e.g. v1.89.1]

**Additional context**
I have solved this by running the following command:
```shell
chmod +x $HOME/.vscode/extensions/cl.eide-3.17.0/res/tools/linux/unify_builder/unify_builder
```
Did you forget to set the proper permission?

**Comment by github0null** [comment]
已在 v3.17.1 revision 中修复
