### ISSUE TITLE
[question] 是否支持編譯靜態函式庫?

### ISSUE THREAD

**Issue by pl168959903** [github0null/eide#341]
**What you want to do**
請問是否有方法支持編譯靜態函式庫

**Describe the problem**
某些例子可能需要編譯函式庫，並引導至其他專案繼續開發。

**Expected behavior**
新增artifact type的選擇項

**Comment by github0null** [comment]
你的意思是 生成 static library 吗？

点击 库 生成器配置，添加要打包的 .o 文件，即可在编译完成后生成 .a 或则 .lib 文件

![image](https://github.com/github0null/eide/assets/43022536/a9ccdbc8-2c52-482a-ad47-d83cd4b8e379)
