### ISSUE TITLE
[question] 如何添加一款cortex-m内核的芯片？

### ISSUE THREAD

**Issue by FlyyingPiggy2020** [github0null/eide#346]
我想在Ubuntu上编译下载仿真一款国产的芯片。
https://www.lnchip.com/index.php?ac=Article&at=List&tid=274#p1

用gcc去编译，dap-link仿真。

请问我应该如何去做？

**Comment by FlyyingPiggy2020** [comment]
这款芯片用MDK是可以烧录的。
我可以找到FLM文件。

**Comment by github0null** [comment]
有 MDK 例程的话可以直接导入，没有例程的话，按照文档 https://em-ide.com/docs/getting-started/new_prj 新建空项目
