### ISSUE TITLE
jlinkv7.96k 在ubuntu上使用时，它不叫JLink而是JlinkExe

### ISSUE THREAD

**Issue by FlyyingPiggy2020** [github0null/eide#347]
`/usr/bin/JLink -ExitOnError 1 -AutoConnect 1 -Device STM32L051K8 -If SWD -Speed 8000 -CommandFile /home/lxf/cortex-m/STM32L051K8/build/Debug/commands.jlink`

这样子无法下载需要改成下面这样才行。

`/usr/bin/JLinkExe -ExitOnError 1 -AutoConnect 1 -Device STM32L051K8 -If SWD -Speed 8000 -CommandFile /home/lxf/cortex-m/STM32L051K8/build/Debug/commands.jlink`

不清楚是版本问题，还是环境不同导致的。

**Comment by FlyyingPiggy2020** [comment]
[jlinkv7.96](https://www.segger.com/downloads/jlink/#J-LinkSoftwareAndDocumentationPack)

**Comment by FlyyingPiggy2020** [comment]
[64-bit DEB Installer](https://www.segger.com/downloads/jlink/JLink_Linux_x86_64.deb)

**Comment by github0null** [comment]
自己创建软链接
