### ISSUE TITLE
不能很好的支持clangd智能提示

### ISSUE THREAD

**Issue by gongshuxuelang** [github0null/eide#350]
我在使用clangd插件配合eide使用发现clangd不能找到单片机的头文件，使用C/C++就可以，但是使用C/C++又不能很好的进行代码折叠，所以我选择使用clangd，虽然找不到头文件，但是不影响编译，希望能够解决这个问题，谢谢。
![image](https://github.com/github0null/eide/assets/42308395/e44ce790-ecb5-4b7a-af72-ccf7e77ef24d)

**Comment by github0null** [comment]
这不是该插件的问题，要使用 clangd，前提是你的项目能用 gcc 或者 clang 编译，否则 clangd 无法识别某些关键字或特殊语法
