### ISSUE TITLE
[这个eide的编译相关配置有什么讲究吗] 

### ISSUE THREAD

**Issue by homohifi** [github0null/eide#364]
**What you want to do**
A clear and concise description of what you want to do.

**Describe the problem**
我是做飞控的一个姿态解算，用QEKF（就RM的王洪玺）为什么一模一样的工程，姿态解算算法在Keil环境下跑150us，在EIDE下要760us。

**Expected behavior**
配置出和Keil下一样快的算法运行效果

**Comment by homohifi** [comment]
<img width="403" alt="EIDE配置" src="https://github.com/user-attachments/assets/00dd5d40-faf2-4b47-a360-7812ec6e96f0">
这里是我的EIDE配置，可能的可以提供工程以及详细说明

**Comment by github0null** [comment]
打开 构建器选项，检查根 优化等级 相关的选项是否跟 keil 上的一样

![image](https://github.com/user-attachments/assets/5f7913a6-a604-448f-b696-2283cffa0795)

如果没有找到问题，你把你导入的 uvprojx 文件发上来

**Comment by homohifi** [comment]
> 打开 构建器选项，检查根 优化等级 相关的选项是否跟 keil 上的一样
> 
> ![image](https://private-user-images.githubusercontent.com/43022536/358853156-5f7913a6-a604-448f-b696-2283cffa0795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NDU2ODAsIm5iZiI6MTcyMzk0NTM4MCwicGF0aCI6Ii80MzAyMjUzNi8zNTg4NTMxNTYtNWY3OTEzYTYtYTYwNC00NDhmLWI2OTYtMjI4M2NmZmEwNzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDAxNDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NGE1MGNhMDAxZGIxZWE2ZjQ1ZGFkMGRlMjU4MzQyNzk3ZmQ1OTg1Y2U5NWRjZTdjNmFkZTVkNzdlY2RiNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_ms_UmTdU-lxVFU1LOtACCY_Oh9wVVVL2MVVXPR0DE)
> 
> 如果没有找到问题，你把你导入的 uvprojx 文件发上来
<img width="1832" alt="EIDE配置" src="https://github.com/user-attachments/assets/9234ba3a-d264-419c-8111-08da91e61b2f">
<img width="319" alt="Keil配置" src="https://github.com/user-attachments/assets/16461278-34d7-45ad-9645-83d8c9d162e4">
我不清楚这样对不对

**Comment by homohifi** [comment]
然后这个需要发送整个工程吗，还是只要一个uvprojx 文件呀

**Comment by github0null** [comment]
只需 uvprojx 文件就行

**Comment by homohifi** [comment]
我的uvprojx文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "github0null/eide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月18日(星期天) 中午12:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [github0null/eide] [这个eide的编译相关配置有什么讲究吗]  (Issue #364)





 
只需 uvprojx 文件就行

**Comment by homohifi** [comment]
> 只需 uvprojx 文件就行

哥，怎么样了呀

**Comment by github0null** [comment]
没看到你的文件，麻烦再发一下

**Comment by homohifi** [comment]
[Uploading IMU_with_FREERTOS.zip…]()

**Comment by homohifi** [comment]
> 没看到你的文件，麻烦再发一下

收到了吗

**Comment by homohifi** [comment]
> 链接是无效的，在论坛上开帖子吧，
> 
> 顺便把你用 mdk 编译后的 map 文件 和 用 eide 编译后的 map 文件也发一下

通过百度网盘分享的文件：map_uvproj
链接：https://pan.baidu.com/s/1ncUY_xCLNbsdHW-r8JbCAg?pwd=2zma 
提取码：2zma 
--来自百度网盘超级会员V5的分享

**Comment by github0null** [comment]
两个工程用的库不一样

![image](https://github.com/user-attachments/assets/206c265d-aeb2-4635-9f32-c54037b00b29)

eide 上，你需要使用排除功能，把不带 f 后缀的lib排除掉，带 f 的才是你要用的，使用硬件浮点，速度才会变快

![image](https://github.com/user-attachments/assets/77d4e6fc-0e04-4075-ada8-be5e959bbca1)

**Comment by github0null** [comment]
另外你 keil 里设置的可能有问题，不带 f 的需要排除掉，这样 eide 导入时才会自动设置排除

keil 上编译后没问题，因为你这个两个文件的顺序，带 f 的在前面，缺少的符号在这个库中被找到先被链接了，所以后面那个库直接跳过了

![image](https://github.com/user-attachments/assets/b4ca4f74-5d22-4a0b-a86c-cf6ce90e7c30)

**Comment by homohifi** [comment]
> 两个工程用的库不一样
> 
> ![image](https://private-user-images.githubusercontent.com/43022536/360360493-206c265d-aeb2-4635-9f32-c54037b00b29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTc3MzAsIm5iZiI6MTcyNDMxNzQzMCwicGF0aCI6Ii80MzAyMjUzNi8zNjAzNjA0OTMtMjA2YzI2NWQtYWViMi00NjM1LTlmMzItYzU0MDM3YjAwYjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOWI0ZmRiMTU2ZWNmNDc2OGVhYjczYTVkNDc1ZThjNGU4M2Y1YjJhYmMwNzE0Y2RlYjdmZGM4ZWZmYjJiNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rPxsows1pXwuH6_Ou4dTmMX9DY7I6vKvU_dIPwYZLVI)
> 
> eide 上，你需要使用排除功能，把不带 f 后缀的lib排除掉，带 f 的才是你要用的，使用硬件浮点，速度才会变快
> 
> ![image](https://private-user-images.githubusercontent.com/43022536/360358826-77d4e6fc-0e04-4075-ada8-be5e959bbca1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTc3MzAsIm5iZiI6MTcyNDMxNzQzMCwicGF0aCI6Ii80MzAyMjUzNi8zNjAzNTg4MjYtNzdkNGU2ZmMtMGUwNC00MDc1LWFkYTgtYmU1ZTk1OWJiY2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NzFiMGI0MTg2ZWU0ZTg4NTZjZGE5MzY4NjRjMjg1ZWRiNDA5MGU3MzYyZDg3YzZkYjU5MGEzYTViYjBkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QtUrtcLW6JGJU6FiQLLlTK7PH9vY7NuC7Zk3uTkDbiY)
解决了，太感谢了！
