### ISSUE TITLE
怎么默认生成hex,使用stlink烧录

### ISSUE THREAD

**Issue by zxyacg** [github0null/eide#365]
每次打开新项目，总是要重新配置生成hex,然后切换stlink烧录，请问应该在哪里可以让他默认设置，还有路径有中文，不能执行代码，这个问题有办法解决吗？
![image](https://github.com/user-attachments/assets/f8e486ef-ab76-4350-9a94-59d38fbb7f27)

**Comment by github0null** [comment]
选完了点一下右上角保存

**Comment by zxyacg** [comment]
肯定保存了，但是要换一个新项目，就又变回去了，我所有项目都要生成hex，所以我想让他默认就生成

**Comment by github0null** [comment]
这个选项是根据你导入的 uvprojx 文件的内容决定的，
如果 uvprojx 文件里有 \<AfterMake\>字段，就会默认禁用内置的 hex 输出功能
