### ISSUE TITLE
[question] STlink能编译但是不能烧录

### ISSUE THREAD

**Issue by Sevenmike7** [github0null/eide#366]
**What you want to do**
与STlink的链接正常，且编译正常但是烧录失败，请问该怎么解决呢

**Describe the problem**
VScode报错
Error: Unable to list supported devices
Error: Cannot identify the device

**Expected behavior**
![image](https://github.com/user-attachments/assets/2f0f7fac-cedf-4d92-a012-83fb59821c5a)
![image](https://github.com/user-attachments/assets/7c6b560e-ab12-4e50-abe9-6ce767dbd1d4)
![image](https://github.com/user-attachments/assets/dd1fce86-01ff-44a3-a9fe-06391475de54)

**Comment by github0null** [comment]
@Sevenmike7 

已回复：https://discuss.em-ide.com/d/757-stlink/2
