### ISSUE TITLE
[question]     像是由于debugHardFault的汇编指令asm("bx lr");使用后编译报错，报错如下图显示，该如何处理呢

### ISSUE THREAD

**Issue by homohifi** [github0null/eide#367]
<img width="767" alt="汇编指令编译错误" src="https://github.com/user-attachments/assets/b6b422a8-a5ab-43ad-934b-46628fbcbaea">
**What you want to do**
A clear and concise description of what you want to do.
在遇到HardFault时我们通常希望定位是什么问题触发了它，所以会使用汇编指令asm("bx lr");，而我在使用后编译发生了不理解的报错
**Describe the problem**

**Expected behavior**
如何能够在EIDE环境下顺利使用汇编指令asm("bx lr");

**Comment by github0null** [comment]
这个是编译器报错，检查你的用法是否存在问题
