### ISSUE TITLE
[question] EIDE AVR SUPPORT ?

### ISSUE THREAD

**Issue by Electronic-6502** [github0null/eide#369]
In some places it is said that EIDE supports AVR, but in some cases it is said that it does not support it, which one is correct?

**Comment by github0null** [comment]
First, install avr-gcc compiler on your pc, and register compiler into system PATH

If your system is win32, we can provide a gcc binary:

![image](https://github.com/user-attachments/assets/0d58184e-6a11-46f6-ae64-6a956a33edc3)


Then you can create an example project from internal template:

![image](https://github.com/user-attachments/assets/8a61c330-3dd8-4605-bfe3-9e14232c27ad)

setup your mcu name:

![image](https://github.com/user-attachments/assets/7c70019d-9726-4caf-8165-7b483de0aada)

build

![image](https://github.com/user-attachments/assets/c3a23f90-a6a2-4711-b601-88e33903a0bb)

have fun !

----

You can also create a empty project and then copy some example code from: 

https://github.com/hexagon5un/AVR-Programming

![image](https://github.com/user-attachments/assets/7ea9df52-61c9-4389-8eef-c89b559071ac)

**Comment by Electronic-6502** [comment]
Thank you for Answer!

در تاریخ دوشنبه ۹ سپتامبر ۲۰۲۴،‏ ۲۱:۲۷ null ***@***.***> نوشت:

**Comment by Electronic-6502** [comment]
Thanks !
I Installed AVR-GCC and Compiled a Project using Em-IDE Plugin , and Nice Worked !
Em-IDE is Very Good Plugin !
