### ISSUE TITLE
[bug] libusb not found in pyocd

### ISSUE THREAD

**Issue by 3verness** [github0null/eide#372]
**What are you doing?**
I'm trying to flash a stm32 using pyocd with stlink.

**Describe the bug**
libusb not found when clicking flash button in EIDE projects. I have copied libusb.dll to System32. And the command can run directly in VSCode terminal.

**To Reproduce**
1. Install pyocd from pip
2. Copy libusb.dll into system32 folder
3. Open a stm32 project and build it
4. Flash

**Expected behavior**
Flash successful.

**Screenshots**
Run from eide:
![image](https://github.com/user-attachments/assets/85b33492-8f51-4613-ba60-3663c00779c9)
Run from terminal:
![image](https://github.com/user-attachments/assets/1fed0fec-6282-4b00-baca-8c4ad62e84c1)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 22631.4037
 - EIDE Version v3.19.6
 - VSCode Version v1.92.2
 - pyocd Version v0.36.0

**Additional context**
some logs, like: `<user_home>/.eide/cl.eide.log`

**Comment by github0null** [comment]
Hello

Make sure **just one python version** on your computer

Perhaps you should refer to this issue: https://github.com/pyocd/pyOCD/issues/696

Sometimes you may need to restart your computer for this type of environment setup problem.
