### ISSUE TITLE
[question] 希望预处理宏定义能通过双击的方式修改条目

### ISSUE THREAD

**Issue by Antecer** [github0null/eide#382]
![image](https://github.com/user-attachments/assets/28696a0d-cafd-410b-a4d1-2172d59d3e7d)

目前只能删除之前的条目，再重新添加，就比较麻烦。
如图，能否实现双击条目或者弄个编辑按钮的方式修改宏定义？这样比较方便。

**Comment by github0null** [comment]
可以使用这个方法修改：

https://em-ide.com/docs/modules/project_attr#%E6%9B%B4%E6%94%B9%E5%B1%9E%E6%80%A7

**Comment by Antecer** [comment]
哦，原来如此，不过，还是没有直接双击修改指定条目来的方便哈。
另外，能否把eide自动生成的文件都挪到 `.eide/` 目录里面(如：.eide.usr.ctx.json, RTE_Components.h)，不要污染工程。
