### ISSUE TITLE
[question] pyocd烧写自定义pack时无法选择目标芯片名称

### ISSUE THREAD

**Issue by nocodo189753** [github0null/eide#385]
**What you want to do**
点击烧写按钮能正确下载固件

**Describe the problem**
pyocd 无法在线安装的芯片型号可以通过命令行指定pack文件路径烧写，但是EIDE UI上无法填入具体型号，如果填入到附加命令行中又会被UI配置覆盖导致无法点击烧写。

不支持的型号只能设置成cortex-m，点击下载时命令行如下，烧写失败
![PixPin_2024-10-30_15-51-00](https://github.com/user-attachments/assets/b678f985-d1c6-4388-9f77-ed57d9e0ddd5)

手动执行，去掉UI的设置，烧写成功
![PixPin_2024-10-30_16-08-22](https://github.com/user-attachments/assets/6454fb14-98ad-4205-90c8-be3dd113f747)

**Expected behavior**
UI上的芯片型号可以手动设置

**Comment by github0null** [comment]
你可以在配置文件里添加 pack 路径，然后再点击 UI 就有了

pyOCD 的配置文件格式它的官网上有介绍

![image](https://github.com/user-attachments/assets/ef8b7a0e-5f6f-4c02-aa87-8bb2516cbf70)

---

如果你需要完全自定义的命令，你需要使用 Shell 模式烧录，可以执行任意的命令，或者 shell 脚本

**Comment by nocodo189753** [comment]
按照你的方法可以烧写了。

不过在vscode 工作目录与EIDE工程文件目录不一致时，无法在yaml里使用pack的相对路径，应该是eide解析yaml时使用EIDE工程文件目录，烧写时shell使用的是vscode打开的文件夹目录

**Comment by github0null** [comment]
这个插件执行命令时的相对路径是以 **当前工程的根目录（项目文件  \*.code-workspace 所在的目录）** 作为基准

不是配置的存放目录

**Comment by nocodo189753** [comment]
是的，yaml文件里以code-workspace文件位置设置pack的相对路径，UI上能正确显示、设置芯片型号，但是点击下载时，pyocd会显示找不到pack包，只能用绝对路径形式。我的工程目录结构如下, vscode打开的是顶层目录
> test_prj
|--src_share_lib
|--prj1
|--|--src
|--|--prj
|--|--|--EIDE
|--|--|--|--eide.code-workspace
|--|--|--|--...
|--|--|--MDK
