### ISSUE TITLE
[question] EIDE打开一个新的项目时，是否可以自动切换vs code 工作区？

### ISSUE THREAD

**Issue by lihebb** [github0null/eide#388]
**What you want to do**
![image](https://github.com/user-attachments/assets/090a7a52-2ba6-4ebe-88a9-6b8e683dde25)

**Describe the problem**
EIDE在已经打开了一个项目的情况下，如果重新打开一个新的项目，在弹出上面切换工作区的对话框时忘记点继续了。

那么vs code工作区还保持在上一个项目的状态，那些打开的文件还是上一个项目的文件。这个时候如果对文件进行编辑，改动的其实是上一个项目的文件。

请问有什么好的方法可以规避这个问题吗？比如是否可以在打开一个新的项目时自动切换工作区呢？

**Expected behavior**

**Comment by github0null** [comment]
你可能需要这个插件：它可以帮你管理你常用的工作区，你直接切换就行了，eide 会自动加载工作区内的项目

https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager

![image](https://github.com/user-attachments/assets/ed248c5b-ef0f-42e1-b9c2-3be19e45b07d)
