### ISSUE TITLE
[question] More compiler supported?

### ISSUE THREAD

**Issue by pengweiplus** [github0null/eide#389]
Embedded IDE For VScode is an exciting project, and I am very interested in disassembly code. Unfortunately, it does not support the compiler toolchain I am currently using. Should "disassembly code" be made as a separate plugin, or should we consider supporting more? I think I can provide some support.

**Comment by github0null** [comment]
您好，请问你使用的何种编译器，现在这个插件支持 gcc 和 armcc
这个插件的反汇编功能比较简单，需要编译器套件本身支持反汇编工具，然后执行一些命令来完成反汇编
这个插件是All In One的，因此这个功能暂时不会分离出来作为独立插件

---

这个插件的相关实现在此处
https://github.com/github0null/eide/blob/master/src/EIDEProjectExplorer.ts#L5530

**Comment by github0null** [comment]
暂时关闭
