### ISSUE TITLE
[bug] 找不到生成的.d文件

### ISSUE THREAD

**Issue by aefj11** [github0null/eide#396]
一、是否可以正确编译
使用mdk可以正常编译
![image](https://github.com/user-attachments/assets/5d4b91be-2999-4b2f-a22d-4560dec3d392)
二、使用eide的相关配置及文件
1.包含的目录
![image](https://github.com/user-attachments/assets/d0b05bfa-6e23-4f2a-a3b0-c54ef47f0ac4)
2.头文件
![image](https://github.com/user-attachments/assets/5ec3ee69-4770-4627-adb4-f995e4ba0d81)
3.源文件
![image](https://github.com/user-attachments/assets/da88716c-f0b2-44c9-b751-3ee07a5f2c58)
三、编译错误
![image](https://github.com/user-attachments/assets/fee88928-a080-4930-b02b-297c3947f125)
四、存在的疑问
因为是初学者，对整体编程不太熟悉，可能犯了比较低级的错误，但是我目前已知的排查只能做到这里，如果问题比较低级，也请麻烦帮帮忙，非常感谢

出现该报错后，首先去排查了源文件是否存在，检查为：存在
排查头文件是否存在，检查为：存在
是否进行了包含操作，检查为：已包含

因为刚开始学，所以怀疑.d文件为将文件编译后生成的文件，尝试过修改目录名称，因目录名称包含中文（尝试修改，未生效）
总之尝试过各种力所能及的办法，没有解决，所以想请您帮帮忙，非常期待及感谢您的回答

**Comment by github0null** [comment]
项目名称，target 名称中不要含有中文

**Comment by aefj11** [comment]
> 项目名称，target 名称中不要含有中文

确实是中文惹得祸，一直不知道怎么修改，全局搜索修改了下解决了，感谢
