### ISSUE TITLE
编译的时候提示许可证相关问题

### ISSUE THREAD

**Issue by shaowp** [github0null/eide#4]
编译的时候提示如下：
[ INFO ] --------------------Start Compile...--------------------

 > Compile: main.c...
Error: C9555E: Failed to check out a license.LICENSE ERROR (R207(3): REGISTRY READ ERROR)

Check that your license details are correct in the License Management dialog of MDK. Additional information is available at:
 http://www.keil.com/support/man/docs/license/license_management.htm
 If you need further help, provide this complete error report to your supplier or license.support@arm.com.
 - ARMLMD_LICENSE_FILE: unset
 - LM_LICENSE_FILE: unset
 - ARM_TOOL_VARIANT: unset
 - ARM_PRODUCT_PATH: unset
 - Product location: C:\Users\Shaowp\.vscode\extensions\cl.eide-1.0.2\bin\ARM\ARM_BIN\ARM\sw\mappings
 - Toolchain location: C:\Users\Shaowp\.vscode\extensions\cl.eide-1.0.2\bin\ARM\ARM_BIN\ARM\ARMCC\bin
 - Selected tool variant: mdk_std
 - Checkout feature: LIC0=KA...-.....-.....
 - Feature version: 5.0201709
 - Keil error code: 1
Product: MDK Plus 5.26
Component: ARM Compiler 5.06 update 6 (build 750)
Tool: armcc [4d3637]

 ERROR  生成错误 : Unknown Error On:  C:\Users\Shaowp\.vscode\extensions\cl.eide-1.0.2\bin\ARM\ARM_BIN\ARM\ARMCC\bin\armcc.exe

**Comment by github0null** [comment]
这个问题已在在新版本中解决，后续将会发布
