### ISSUE TITLE
针对不同的编译器可设置不同的scatter文件

### ISSUE THREAD

**Issue by heartacker** [github0null/eide#42]
不同的编译器这个文件不一样的，希望可以针对单独的编译器设置不同的文件，不然切换编译器就找不到文件了

**Comment by github0null** [comment]
切换编译器，scatter 路径需要重新设置，*.sct 对应 ARMCC ，*.ld 对应 GCC，就这两种

**Comment by heartacker** [comment]
> 切换编译器，scatter 路径需要重新设置，_.sct 对应 ARMCC ，_.ld 对应 GCC，就这两种

明白你的意思,arm 和gcc,其实arm A5和A6 还是不同的,比如S32K 官方就提供不同的sct文件.
我希望的是说这个项目能单独对应不同的编译器,每个编译器都需要自己设置, 这样用户切换的时候,不需要再次更改,方便用户直接切换不同的编译器就可以直接编译,非常感谢
![image](https://user-images.githubusercontent.com/1876302/89307701-f7956d80-d6a3-11ea-96bf-ca9f76466c5a.png)

**Comment by github0null** [comment]
这些配置都是直接转化为 json 保存的，要为每一种编译工具保存一份比较麻烦，你切换了就必须要重新再设置；
而且也不能总切来切去的吧，在开始项目之前就应该确定好要用哪种工具链
