### ISSUE TITLE
OpenOcd 下载时错误

### ISSUE THREAD

**Issue by Suvian-wy** [github0null/eide#45]
在下载时，点击下载按钮之后，调用OpenOCD的命令错误，导致OpenOcd无法识别 .hex 文件的目录
 D:\Environment\openocd-0.10.0\bin\openocd.exe -f interface/stlink-v2.cfg -f target/stm32f4x.cfg -c "init" -c "reset init" -c "program \"d:\\\\WorkSpace\\\\EIDEProject\\\\BootLoader\\\\out\\Release\\\\BootLoader.hex\\"

指令修改之后是可以的
D:\Environment\openocd-0.10.0\bin\openocd.exe -f interface/stlink-v2.cfg -f target/stm32f4x.cfg -c "init" -c "reset init" -c "program \"d:/WorkSpace/EIDEProject/BootLoader/out/AC5/BootLoader.hex\\"  verify reset exit"

**Comment by github0null** [comment]
没有发现问题
***
![截图20200827220739](https://user-images.githubusercontent.com/43022536/91453367-33da7900-e8b2-11ea-85b9-575ef71508b6.png)

**Comment by github0null** [comment]
已经打算将传递给 openocd 的路径调整为 unix 格式来避免这种问题
