### ISSUE TITLE
Openocd 下载

### ISSUE THREAD

**Issue by Suvian-wy** [github0null/eide#46]
openocd 下载时，能不能加一个 run to main 的选项，现在是需要手动复位的

**Comment by github0null** [comment]
不是每种下载工具都提供 RunAfterProgram 选项，你可以试试 STLink；
openocd 下载结束后已经执行了复位命令，你应该可以在命令行的最后看到；
至于是否真的发生了复位，那就不知道了, 毕竟插件只是负责发送命令
