### ISSUE TITLE
请问这个项目有支持使用串口进行下载吗

### ISSUE THREAD

**Issue by wyh0106** [github0null/eide#49]
这是个很好的项目，作为一个stm32的初学者，通过解决使用这个插件的过程中遇到的问题，基本上对工程文件的几乎每个部分都有了一定程度的了解。不过我使用的开发板有usb串口，相比起usb的串口，stlink的jtag接线实在是太麻烦了，不仅线多，而且还得外接电源。所以我希望能有一个支持usb串口下载的功能。

**Comment by github0null** [comment]
因为不同的芯片厂家会烧录不同的 bootloader，因此串口没有统一的下载程序

**Comment by github0null** [comment]
使用 STLink SWD 方式下载只需要接 3 根线即可

**Comment by wyh0106** [comment]
> 使用STLink SWD方式下载只需要接3根线即可

这样啊，彳亍口巴。
