### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by hblslt** [github0null/eide#5]
安装完成后，编译时显示如下错误：

E:\STM32WS\Template\EIDE\Demo>& 'c:\Users\Administrator\.vscode\extensions\cl.eide-1.0.4\bin\ARM\ARM_Builder.exe' -b 'd:\keil\MDK526' 'e:\STM32WS\Template\EIDE\Demo\.\out\Demo.params'o.params'
此时不应有 &。

**Comment by github0null** [comment]
终端应该用 Powershell 而不是 CMD
