### ISSUE TITLE
请问怎么创建一个工程模板

### ISSUE THREAD

**Issue by wyh0106** [github0null/eide#50]
我找了很久没找到怎么把一个工程导出成模板。

每次创建新工程只能用默认的工程模板，然后走一遍以下流程：
1. 修改默认的芯片型号。
2. 添加串口的外设资源文件。
3. 修改烧录模式。
4. 把那个库文件夹拖进来。
5. 添加进工程。
6. 添加头文件路径。

我想也许可以增设一个“导出工程为模板”按钮在OPERATION栏里面，这样方便用户使用自己的模板。

**Comment by github0null** [comment]
有一个 导出模板 按钮，在使用手册中说的很清楚------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Rasputin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月28日(星期一) 晚上10:05
收件人:&nbsp;&quot;github0null/eide&quot;<eide@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[github0null/eide] 请问怎么创建一个工程模板 (#50)
