### ISSUE TITLE
ARM uvproj support. 

### ISSUE THREAD

**Issue by SadE54** [github0null/eide#51]
Hi,

Firstly, thanks for this cool plug in!
I have a very big project using the old format uvproj. So it seems I cannot import it into the plug-in 😕 Is it a big deal to transform a uvproj to uvprojx format? I took a look at the xml and it seems it's almost the same except packages ( that I don't use). What I have to change manually to be able to import it in Eide?

Regards,

Yann

**Comment by github0null** [comment]
**import from keil project** is not support in Eide, please use the latest version !
