### ISSUE TITLE
请问串口调试有输出的功能吗？

### ISSUE THREAD

**Issue by wyh0106** [github0null/eide#54]
如果没有，作者能考虑做一个吗？

**Comment by github0null** [comment]
你好，串口助手具有完整的接收发送功能，使用过程中遇到什么问题了吗

**Comment by wyh0106** [comment]
是这样的,我在使用手册中查到似乎是可以配置收发模式，但我在设置里并没有找到，请问如何打开串口发送模式。

**Comment by wyh0106** [comment]
> 你好，串口助手具有完整的接收发送功能，使用过程中遇到什么问题了吗

是这样的，我在使用手册中查到似乎是可以配置收发模式，但我在设置里并没有找到，请问如何打开串行发送模式。

**Comment by github0null** [comment]
集成在一起了，可以直接输入，就跟命令行一样，所以这个设置没有用了
