### ISSUE TITLE
生成.hex文件时出现错误

### ISSUE THREAD

**Issue by mengzhuozhuo** [github0null/eide#6]
*** ERROR L257: UNKNOWN

 ERROR  生成失败(build Failed) : Link Error

**Comment by github0null** [comment]
有完整的命令行截图吗

**Comment by mengzhuozhuo** [comment]
PS C:\Users\asus\Desktop\C51_programe\Target 1> & 'c:\vscode\extensions -s 'c:\Users\asus\Desktop\C51_programe\Target 1\.\src\Source Group 1' 
Group 1;c:\Users\asus\Desktop\C51_programe\Target 1\.\dependence\build-uild-in\STD;d:\software\Keil\C51\INC' -d 'c:\Users\asus\Desktop\C51_pro

[ INFO ] Source file list:


 WARNING  Not found C51 Startup File! File must be named like this: xxx

> C File:  c:\Users\asus\Desktop\C51_programe\Target 1\.\src\Source Gro

[ INFO ] --------------------Start Compile...--------------------


C51 COMPILER V9.60.0.0 - SN: T1UMC-G5KF4C
COPYRIGHT Copyright (C) 2012 - 2019 ARM Ltd and ARM Germany GmbH. All r

C51 COMPILATION COMPLETE.  0 WARNING(S),  0 ERROR(S)

--------------------------------------------------------

******************************************************************************
* RESTRICTED VERSION WITH 0800H BYTE CODE SIZE LIMIT; USED: 0001H BYTE ( 0%) *
******************************************************************************

Program Size: data=9.0 xdata=0 const=0 code=16
*** ERROR L257: UNKNOWN

 ERROR  生成失败(build Failed) : Link Error

**Comment by mengzhuozhuo** [comment]
![批注 2019-11-18 123628](https://user-images.githubusercontent.com/56299368/69025000-1d88be00-0a00-11ea-8658-f2d9e33efaa7.jpg)

**Comment by github0null** [comment]
看起来并不是插件本身的问题，插件调用的是 Keil 编译器，
帮你找到了一个 链接， 上面好像有 和你一样的问题， [here](https://community.cypress.com/thread/44542)

**Comment by github0null** [comment]
可能是没有完全破解 Keil，还存在代码限制

**Comment by github0null** [comment]
建议先导出 Keil 项目在keil 上编译一下，如果能过，那应该是我的构建工具有问题，

**Comment by mengzhuozhuo** [comment]
keil上也不能编译，我再重装试一试。麻烦你了

**Comment by mengzhuozhuo** [comment]
![image](https://user-images.githubusercontent.com/56299368/69037658-3787c800-0a23-11ea-89c3-7bbb8934176a.png)
我发现导出的项目只要把这两个选项去掉就可以编译通过，我在vscode上改怎么做？

**Comment by mengzhuozhuo** [comment]
![批注 2019-11-18 165016](https://user-images.githubusercontent.com/56299368/69037817-8a617f80-0a23-11ea-9e50-2f99a7ed3bd1.jpg)
我发现导出的项目只要把这两个选项取消就可以编译，在vscode上应该怎么做？

**Comment by github0null** [comment]
这个插件只使用 LX51 做链接器， AX51做汇编器, 暂时没法更改，因为 LX51 功能更加强大

**Comment by mengzhuozhuo** [comment]
那我改用其他版本的keil是不是就可以了？

**Comment by github0null** [comment]
不知道，具体看你代码中写了什么，我已经编译过很多C51项目了，都是没问题的， 后续我将会加入一些可修改的编译参数到插件中，增强插件的功能，

> 如果可以的话，你可以把你出问题的工程打包发我，这样可以帮助我改进这个插件，让它变得更可靠，稳定，谢谢

**Comment by mengzhuozhuo** [comment]
[test.zip](https://github.com/github0null/eide/files/3857927/test.zip)

我的代码什么也没写，应该是我操作有问题，你要是有空的话帮我看一下。谢谢

**Comment by github0null** [comment]
> 在我的电脑上没问题的，其实也不用纠结这些， 实在不行，在keil 上编译也可以的
![image](https://user-images.githubusercontent.com/43022536/69042410-1ecfe000-0a2c-11ea-938c-9093369c7683.png)

**Comment by mengzhuozhuo** [comment]
嗯，麻烦你了

**Comment by tinyhugh** [comment]
我这边碰到和你一样的情况，后来发现是权限问题，如果你是使用注册机，可以选择Prof. Developers Kit (Plus)，留下此解决办法帮助后来人。
