### ISSUE TITLE
Git 不友好

### ISSUE THREAD

**Issue by iamapig120** [github0null/eide#61]
eide.json miscInfo 对象 下的 lastTelTime 和 lastBuildTime 因尝试编译而经常被更新，造成每次 release 时几乎都要手动去掉这个文件，对于这样一个重要的【配置文件】，是否应该考虑将这种类似 log 性质的记录内容移出该文件？

**Comment by github0null** [comment]
lastBuildTime 后续版本会去掉，

lastTelTime 和编译无关，不是随着编译在变动的

**Comment by github0null** [comment]
v1.22.0已经去掉了这些字段
