### ISSUE TITLE
功能需求：串口监视器输出HEX格式

### ISSUE THREAD

**Issue by ma6254** [github0null/eide#62]
嵌入式调试场景中，串口监视器HEX格式输出是必要的，经常会有调试二进制通讯协议的需求
本想修改源代码，发现你并未开源，可否做出以下修改：
- 可以设置外部串口监视器软件，参数通过模板字符串提供
- 修改"SerialPortMonitor.exe"，该工具给`-h`、`-H`、`--help`参数后均无输出帮助信息，给`-H`、`-X`显示`Too few parameters !`，不确认其是否支持HEX格式输出，可否添加HEX格式输出支持

**Comment by github0null** [comment]
- 这个你可以暂时使用 vscode task 去调用自定义的串口程序，
- 后面的版本里 eide 也会允许你使用自定义的串口程序

**Comment by ma6254** [comment]
问题未解决
