### ISSUE TITLE
RTX51 Tiny

### ISSUE THREAD

**Issue by motiontek** [github0null/eide#63]
Can not specify "operating system " as RTX-51 Tiny, how to do this : BL51 *.obj RTXtiny.lib etc. thanks

**Comment by github0null** [comment]
go to **compiler options** -> **linker**

modify field "use-RTX"  's value to "RTX-Tiny"

![image](https://user-images.githubusercontent.com/43022536/105577576-79459880-5db5-11eb-856d-e7ab7c59c4d0.png)
