### ISSUE TITLE
一些优化建议

### ISSUE THREAD

**Issue by heartacker** [github0null/eide#66]
1. 如果当前没有加载项目的时候，能否自动隐藏编译，下载，清除的action icon
2. 能否在operation 添加打开eide的设置的快捷方式呢？
   ![image](https://user-images.githubusercontent.com/1876302/114335687-de708500-9b7f-11eb-84b3-284c9ad5ac1c.png)

比如终端就可以快速打开设置
![image](https://user-images.githubusercontent.com/1876302/114335794-15df3180-9b80-11eb-80d1-b81a2f4b6180.png)

**Comment by github0null** [comment]
嗯嗯，会的
