### ISSUE TITLE
Please co-publish on Open VSIX Registry

### ISSUE THREAD

**Issue by GitMensch** [github0null/eide#69]
See https://github.com/eclipse/openvsx/wiki/Publishing-Extensions for some details. Currently no similar extension is found on open-vsx.org, which is also the default provider for VSCodium (which itself is the packaged vscode build in different GNU/Linux distros).
So far no extension for embedded development is available there and it looks like this extensions would be a nice addition.

**Comment by github0null** [comment]
Okay, but what are the advantages of this thing?

![image](https://user-images.githubusercontent.com/43022536/126964430-58a2fc5e-7282-4d64-82ad-c7e47cab3420.png)

**Comment by GitMensch** [comment]
Thanks!

The advantage is that open-vsx can be used with any vscode based editor (and commonly also with theia as this provides most of the necessary api), while the ms marketplace may explicit only used with "Microsoft Visual Studio Code" (the binaries that are provided my MS and that does not match the vscode repo).
This is also the reason that those normally don't use the MS market place as the users would breach its license.

I can confirm that the extension is now usable in VSCodium. Thank you very much!
