### ISSUE TITLE
此时不应有 &。

### ISSUE THREAD

**Issue by zhouji0212** [github0null/eide#8]
E:\MyDevelop\TestC51\myc51>& 'c:\Users\Administrator\.vscode\extensions\cl.eide-1.0.4\bin\C51\C51_Builder.exe' -b 'c:\Keil_v5' -s 'e:\MyDevelop\TestC51\myc51\.\src' -i 'c:\Keil_v5\C51\INC;e:\MyDevelop\TestC51\myc51\.\dependence\build-in\STD;e:\MyDevelop\TestC51\myc51\.\dependence\build-in' -d 'e:\MyDevelop\TestC51\myc51\.\out' -o '8' -t '0'
此时不应有 &。

**Comment by github0null** [comment]
终端是 powershell
