### ISSUE TITLE
能否直接修改原本工程的文件

### ISSUE THREAD

**Issue by ChansonLeung** [github0null/eide#9]

**Comment by github0null** [comment]
请说的详细些，没明白啥意思

**Comment by ChansonLeung** [comment]
> 请说的详细些，没明白啥意思

导入工程之后，我修改的源文件是插件自己新拷贝的一份源文件，想问下插件支持直接覆盖掉原来的源文件吗？

**Comment by github0null** [comment]
这个**不可以**，因为覆盖原来的文件不是一个很好的做法，万一你没有备份原来的项目那就惨了。

你可以点击导出为 keil ，即可在 eide 项目目录下生成新的 Keil 项目，再用keil打开即可

**Comment by lingex** [comment]
同有这个需求，希望跟MDK项目共存。
CubeMX修改很方便，现在项目被拷贝出来一份，再回头用CubeMX修改了原工程，这样维护起来很麻烦。

**Comment by github0null** [comment]
由于 vscode 工作区和 keil 的项目结构不同， **eide 暂时不能和 Keil 共存**；
