### ISSUE TITLE
对于不同Target的预定义宏，在编辑页面能否应用生效

### ISSUE THREAD

**Issue by bsbandwl** [github0null/eide#95]
问题大概是这样的：
我通过Keil的不同Target来生成不同的目标固件，而程序代码中不同的部分就靠宏来开关。这些宏绑定在不同Target中。
没有使用EIDE时，我在VSCode中，通过编辑c_cpp_properties.json，按照Target编写configurations，控制各个includePath和defines。
![图片](https://user-images.githubusercontent.com/8805497/150461045-a35e1f43-d93f-4148-8c25-46f0ccfeb277.png)
这样我切换不同configuration，实现不同的宏定义切换，保证看的代码正确显示。

用了EIDE后，虽然可以切换Target（我找了好一会儿才找到切换入口），也能查看不同Target的宏，但是VSCode里面显示的代码明显没有同步这个define和includePath。
希望能同步上，这样我完全用EIDE就行，不用自己再去创建configurations。
![图片](https://user-images.githubusercontent.com/8805497/150461394-8bfe78b9-a2cc-4829-aca7-2df938a60b73.png)

谢谢

**Comment by github0null** [comment]
- 如果你使用 `eide`，**不要手动填写** `c_cpp_properties.json`，这个配置是固定不变的，始终为如下内容：
```
{
    "configurations": [
        {
            "name": "win32",
            "configurationProvider": "cl.eide"
        }
    ],
    "version": 4
}
```

- 对于不同的 `target`，预处理器定义都是独立的，你像 keil 那样去操作就行了

**Comment by bsbandwl** [comment]
![图片](https://user-images.githubusercontent.com/8805497/150486120-7e114e12-2433-49f7-bd11-7d34fc865079.png)

我把 c_cpp_properties.json 删除，然后重启软件，EIDE 重建了您上面这样的 c_cpp_properties.json。 确实使用了 cl.eide，但是宏还是没有生效

谢谢

**Comment by github0null** [comment]
我这里是正常的，见下面 gif:

![switch_macro](https://user-images.githubusercontent.com/43022536/150492296-f2a546a9-956f-4f40-bd43-c542981fb5dd.gif)

***

你可以试一试以下步骤：

- 打开 `输出面板`->`eide-cpptools-log` 检查 eide 提供的 `c_cpp_properties` 配置中是否存在该 `宏`

  ![image](https://user-images.githubusercontent.com/43022536/150492721-a31c22e9-621a-4bf5-9c9c-f88b3a595a76.png)

- 如果上一步的 `c_cpp_properties` 配置没有问题，可能是 `C/C++` 插件没有及时刷新导致的，你可以打开命令面板输入以下命令重置数据库试试；

  ![image](https://user-images.githubusercontent.com/43022536/150492930-25e89bd0-0bca-4163-9563-26310e08b0d3.png)

**Comment by bsbandwl** [comment]
我卸载了CMake插件，各种重启，都没在输出面板看到任何信息，只有 eide-log 有输出
![图片](https://user-images.githubusercontent.com/8805497/150507941-e0e1c492-05ef-4114-afe6-5e729d982053.png)
![图片](https://user-images.githubusercontent.com/8805497/150508048-0bdd4cb7-4b66-4023-8ba2-edbfa726589e.png)
![图片](https://user-images.githubusercontent.com/8805497/150508143-ed367067-2461-45f8-853f-41f716653345.png)
发现确确实实没有输出：
![图片](https://user-images.githubusercontent.com/8805497/150508256-87947c28-f470-4b4b-895e-264a56c0f4fd.png)
但是C/C++有警告：
[2022/1/21下午6:07:52] 对于 C 源文件，cStandard 已根据编译器参数和查询 compilerPath 从“c99”更改为“c17”:“D:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe”
![图片](https://user-images.githubusercontent.com/8805497/150508424-fed40ce5-1213-4e7e-92fc-cc1223b68ae4.png)



> 我这里是正常的，见下面 gif:
> 
> ![switch_macro](https://user-images.githubusercontent.com/43022536/150492296-f2a546a9-956f-4f40-bd43-c542981fb5dd.gif)
> 
> 你可以试一试以下步骤：
> 
>     * 打开 `输出面板`->`eide-cpptools-log` 检查 eide 提供的 `c_cpp_properties` 配置中是否存在该 `宏`
>       ![image](https://user-images.githubusercontent.com/43022536/150492721-a31c22e9-621a-4bf5-9c9c-f88b3a595a76.png)
> 
>     * 如果上一步的 `c_cpp_properties` 配置没有问题，可能是 `C/C++` 插件没有及时刷新导致的，你可以打开命令面板输入以下命令重置数据库，然后重启试试；
>       ![image](https://user-images.githubusercontent.com/43022536/150492930-25e89bd0-0bca-4163-9563-26310e08b0d3.png)

**Comment by github0null** [comment]
只要打开了 eide 项目，就会注册 `configurationProvider`，无论注册成功与否，都会存在输出

![image](https://user-images.githubusercontent.com/43022536/150520043-6ce5eca8-876d-4450-8a07-52e85c6983ae.png)

![image](https://user-images.githubusercontent.com/43022536/150520948-e98d3cdf-aec4-4d4f-a78e-395027574b8d.png)

***

> 如果没有使用 eide 提供 c/c++ 配置，代码中的 `#include"xxx.h"` 指令将存在红色波浪线，同时跳转定义等功能也将无法正确跳转至相应位置，如果一切正常，那就没问题，你可以检查一下；

![image](https://user-images.githubusercontent.com/43022536/150521285-92e5656b-7fc9-42fc-9191-023b165d59b1.png)

***

建议先删除整个 eide 安装目录（`C:\Users\<用户名>\.vscode\extensions\cl.eide-2.16.6`）后，重装插件。

如果还不能解决，我也没有好的办法

**Comment by bsbandwl** [comment]
各种折腾之后，删除了整个VSCode，然后重装，只安装C/C++扩展，之后按照EIDE，发现功能正常。说明之前我大量安装的插件中，有一个产生了问题

**Comment by github0null** [comment]
好吧，论坛里也有一个跟你一样，目前不知道什么原因导致的

> 我也检查了一下，除非没有收到 `project.opened` 事件，否则这个一定会产生输出的；而 `project.opened` 事件在项目被打开后就会被立即发出

**Comment by TuRan-sino** [comment]
我也产生了和author一样的问题, 
EIDE还提示了这个信息
![image](https://user-images.githubusercontent.com/51948125/151657436-72a27ce1-da98-4b79-bfd3-500bd92054b7.png)
