### ISSUE TITLE
关于eide的resource下载

### ISSUE THREAD

**Issue by vhext** [github0null/eide#97]
作者是否考虑将资源仓库迁移到国内的平台（gitee）上进行下载以提高下载效率，尽管eide似乎在下载资源时启用了代理，但是下载时还是时不时会失败

**Comment by github0null** [comment]
`gitee api` 和 `github api` 不一样，暂时没法直接移过去

代理有两个，每个 `30M` 带宽，应该够吧，`eide-binaries` 是 `25MB` 左右

> 还有, `gitee` 仓库限制比 `github` 更严格，单文件限制在 `50M`，仓库总大小限制 `500M`，这个仓库里有些压缩包恐怕推送不上去

**Comment by vhext** [comment]
如果只是单个压缩文件过大的话可以尝试压缩包分part，如果是仓库总大小不够确实没啥好办法
