### ISSUE TITLE
C/C++ 插件更新到1.8.2后，eide_cpptols_log没有输出了

### ISSUE THREAD

**Issue by ckforce** [github0null/eide#99]

**Comment by github0null** [comment]
跟插件启动次序有关系，eide 将在项目加载完毕后注册 `configProvider`，如果这时 `c/c++` 插件还未完成启动，注册将失败；

暂时的解决办法：

- 打开 `eide` 安装目录下的 `package.json`，添加如下内容，使得 `c/c++` 插件先于 eide 启动：

  ![image](https://user-images.githubusercontent.com/43022536/152674895-1bb29cd6-f5eb-410f-8317-89ed08a5fb03.png)

**Comment by ckforce** [comment]
感谢！测试过ok！
